### PR TITLE
[Feature] Popup: move related child in corresponding popup_lizmap_dd_relation div

### LINKED ISSUE #4407: [Bug]: popup relation - div popup_lizmap_dd_relation empty in parent
### What is the bug? (in English)

The relationships are not integrated into the parent's popup. I've tested all possible configurations (drag and drop or automatic).

The relationships are properly declared.

The WMS/WFS streams are also.

    I don't understand why the update checkbox is not available even though the user has the rights 😅

The drag and drop forms work fine in QGIS Desktop and in the Lizmap plugin.

The QGIS/QGIS Server versions are equivalent, and the project works perfectly in QGIS Desktop.

My base project is complex, with several tabs and several relationships, but even with a minimal version of the project (1 parent table + 1 child table + 1 nomenclature table), I can't get the correct display of the div in the parent popup.

If I check "Display associated children", the children appear under the parent's popup in their own "compact table" popup, but not in the parent.

I can't do this because the project would be unreadable with all the children cascading.

-----------------------
Bonjour,

Les relations ne sont pas intégrés dans la popup du parent.
J'ai testé toutes les configurations possibles ( drag and drop ou auto)

Les relations sont bien déclarées
image

les flux wms/wfs aussi,
image
> je ne comprends pourquoi la case maj n'est pas dispo alors que l'user a les droits😅 

les formulaires drag and drop ok dans qgis desktop et dans le plugin lizmap
image
image

les version qgis/qgis-server sont équivalentes 
et le projet marche parfaitement dans qgis desktop
image

Mon projet de base est complexe 
image
avec plusieurs onglets et plusieurs relations

mais même avec une version minimale du projet (1 table parent + 1 table enfant + 1 table nomenclature)
je n'arrive pas avoir l'affichage correcte de la div dans la popup parent.
```
<div id="popup_relation_t_reserves_infos_d58fe949_b224_4438_96bd_dad4e936bf15_id_reserve_t_reserves_f2291bf5_b9e1_4c2d_9d3b_25fe30b1f8b2_id_reserve" data-relation-id="t_reserves_infos_d58fe949_b224_4438_96bd_dad4e936bf15_id_reserve_t_reserves_f2291bf5_b9e1_4c2d_9d3b_25fe30b1f8b2_id_reserve" data-referencing-layer-id="t_reserves_infos_d58fe949_b224_4438_96bd_dad4e936bf15" class="popup_lizmap_dd_relation">
  </div>

```
image

Si je coche "afficher les enfants associés", les enfants apparaissent sous la popup du parent dans sa propre popup 'table compacte' mais pas dans le parent 
> je ne peux pas faire cela car le projet serait illisible avec tout les enfants en cascade
image
----

le problème semble venir de tooltip et j'ai peur que ma demande soit reliée avec le 
ticket https://github.com/3liz/lizmap-web-client/issues/3756

Pourriez vous m'indiquer si j'ai loupé une étape ou si ce que je veux faire n'est pas faisable ?
Merci

### Steps to reproduce the issue

1. add a parent table
2. add a relation with child table
3. configure drag and drop
4. hope to see child infos in parent table in popup

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.11
* QGIS Desktop : 3.28.11
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.9.0
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

debian 12.5

### Browsers

Firefox

### Browsers version

125.0.3

### Relevant log output

```shell
12:22:37 INFO Server[37042]: ******************** New request ***************
12:22:37 INFO Server[37042]: Request URL: xxxxx/cgi-bin/qgis_mapserv.fcgi
12:22:37 INFO Server[37042]: Environment:
12:22:37 INFO Server[37042]: ------------------------------------------------
12:22:37 INFO Server[37042]: SERVER_NAME: xxxxxx.org
12:22:37 INFO Server[37042]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi
12:22:37 INFO Server[37042]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
12:22:37 INFO Server[37042]: REMOTE_ADDR: 127.0.0.1
12:22:37 INFO Server[37042]: SERVER_PORT: 80
12:22:37 INFO Server[37042]: QUERY_STRING: 
12:22:37 INFO Server[37042]: CONTENT_TYPE: application/x-www-form-urlencoded
12:22:37 INFO Server[37042]: REQUEST_METHOD: POST
12:22:37 INFO Server[37042]: SERVER_PROTOCOL: HTTP/1.1
12:22:37 WARNING Server[37042]: Error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
12:22:37 INFO Lizmap[37042]: Request headers provided
12:22:37 INFO Lizmap[37042]: No lizmap user groups in request headers
12:22:37 INFO Lizmap[37042]: Lizmap user groups in parameters : admins,users
12:22:37 INFO Lizmap[37042]: Fetching /var/www/html/carto_lizmap/reseau2reserves/minimal_reserve_info.qgs.cfg cfg file with last modified timestamp : 1714731683.0
12:22:37 INFO Lizmap[37042]: No acl defined in Lizmap config
12:22:37 INFO WfsOutputExtension[37042]: requestReady ran in 0.0s
12:22:37 INFO Server[37042]: BBOX:132720.285618,6801154.90295,137108.144394,6803212.307064
12:22:37 INFO Server[37042]: CRS:EPSG:2154
12:22:37 INFO Server[37042]: DPI:96
12:22:37 INFO Server[37042]: FILTER:t_reserves:"id_reserve" IN ( 58 ) 
12:22:37 INFO Server[37042]: FILTERTOKEN:xxxxxxxxxxxxxxxxx
12:22:37 INFO Server[37042]: FORMAT:image/png
12:22:37 INFO Server[37042]: HEIGHT:778
12:22:37 INFO Server[37042]: LAYERS:t_reserves
12:22:37 INFO Server[37042]: LIZMAP_OVERRIDE_FILTER:1
12:22:37 INFO Server[37042]: LIZMAP_USER:admin_pierre
12:22:37 INFO Server[37042]: LIZMAP_USER_GROUPS:admins, users
12:22:37 INFO Server[37042]: MAP:/var/www/html/carto_lizmap/reseau2reserves/minimal_reserve_info.qgs
12:22:37 INFO Server[37042]: REQUEST:getmap
12:22:37 INFO Server[37042]: SERVICE:WMS
12:22:37 INFO Server[37042]: STYLES:default
12:22:37 INFO Server[37042]: TRANSPARENT:true
12:22:37 INFO Server[37042]: TS:1714731756419
12:22:37 INFO Server[37042]: VERSION:1.3.0
12:22:37 INFO Server[37042]: WIDTH:1658
12:22:37 INFO AccessControlFilter[37042]: QgsAccessControlFilter plugin default layerPermissions called
12:22:37 INFO Lizmap[37042]: Request headers provided
12:22:37 INFO Lizmap[37042]: No lizmap user groups in request headers
12:22:37 INFO Lizmap[37042]: Lizmap user groups in parameters : admins,users
12:22:37 INFO Lizmap[37042]: Request headers provided
12:22:37 INFO Lizmap[37042]: No lizmap user login in request headers
12:22:37 INFO Lizmap[37042]: Lizmap user login in parameters : admin_pierre

> Error parsing post data as XML ?

----------
12:22:29 INFO Lizmap[37042]: Fetching /var/www/html/carto_lizmap/reseau2reserves/minimal_reserve_info.qgs.cfg cfg file with last modified timestamp : 1714731683.0
12:22:29 INFO Lizmap[37042]: No edition config defined for layer: t_reserves_infos (t_reserves_infos_d58fe949_b224_4438_96bd_dad4e936bf15)

> why no edition config ? 

----------

12:22:33 INFO Lizmap[37042]: The popup has been replaced for feature ID '58' in layer 't_reserves'
12:22:33 INFO Lizmap[37042]: Replacing the maptip from QGIS by the drag and drop expression for 1 features on t_reserves
12:22:33 INFO Lizmap[37042]: Replacing feature '58' in layer 't_reserves' for the GetFeatureInfo by the drag&drop form
12:22:33 INFO Lizmap[37042]: GetFeatureInfo replaced for project /var/www/html/carto_lizmap/reseau2reserves/minimal_reserve_info.qgs

> seems good to me...

And 0 critical error or bad warning beside xml error
```

### PR DESCRIPTION
**Pull request by mind84**
When a `Popup` is displayed with the QGIS Drag and Drop configuration, for each relations configured in the layout a container HTML element (`div.popup_lizmap_dd_relation`) is added to the Popup (see https://github.com/3liz/qgis-lizmap-server-plugin/commit/6a4240041858883a83baad08012a0604b19c8873)

This PR moves the related child (or children) popup in corresponding `popup_lizmap_dd_relation` div. The feature covers both `1:n` and `n:m` relations 

Ticket : fix #4407

Backport to 3.8

Funded by Faunalia

### CODE REVIEW

**Comment by mind84** [comment]
As side effect, the `background-color` for the children popups is inherited from this rule:

https://github.com/3liz/qgis-lizmap-server-plugin/blob/b17cd00abbdf7b2274c2aea3fafb2c817588553a/lizmap_server/tooltip.py#L447


image

The display effect is to much "heavy" IMHO and could be better.

I guess there are two options here:

1. change CSS rule in `lizmap-server-plugin`
2. let users add custom css.

Since class `popup_lizmap_dd_relation` is never get involved until now, I think that option **1** is the best because there is little chance that adding some specific rules for this class will break the UI of someone

What do you think about it?

**Comment by rldhont** [comment]
@Gustry any advice about the CSS ?

**Comment by mind84** [comment]
@Gustry,

just for trying, I've added a couple of css rules in `tooltip.py`, only for the `relations` case `(groupbox` is good with dark background IMHO):

```css
div.popup_lizmap_dd div.tab-content div.tab-pane div.popup_lizmap_dd_relation div, 
div.popup_lizmap_dd div.tab-content div.tab-pane div.popup_lizmap_dd_relation 
{
    border: 0px;
    border-radius: 0px;
    background-color:white;
}
```
result is:

image

What do you think about it?

Thanks

**Comment by mind84** [comment]
@mdouchin,

I agree, I'm thinking about it too but there's probably a lot work to do and, with the new `feature component` coming, I'm wondering if it's better to focus effort on that.

Anyway, basically with this PR nothing changes :), just put things in the right place (or at least, try to)

Thanks

**Review by rldhont — APPROVED** [review]

**Review by Gustry — APPROVED** [review]

**Pull request merged**
