### PR TITLE
[Bugfix] JS config themes

### PR DESCRIPTION
**Pull request by rldhont**
Fixing JS classes around map themes

Funded by Karum

### CODE REVIEW

**Comment by josemvm** [comment]
hi @rldhont i get this error ``
An error occurred while loading this map. Some necessary resources may temporarily be unavailable. Please try again later.
[Go back to the home page.](https://xxx.xxx.xxx/)
`` when i activate de first map theme on qgis server 3.34, lwc 3.7.9-pre but not on qgis server 3.28

maybe related to this PR (?)

**Comment by rldhont** [comment]
> hi @rldhont i get this error `An error occurred while loading this map. Some necessary resources may temporarily be unavailable. Please try again later. [Go back to the home page.](https://xxx.xxx.xxx/)` when i activate de first map theme on qgis server 3.34, lwc 3.7.9-pre but not on qgis server 3.28
> 
> maybe related to this PR (?)

When you've got this message, it means that one of the GetCapabilities requests (WMS, WFS, WMTS) or all has failed.

**Comment by Gustry** [comment]
@josemvm 

>  i get this error

Please check your Javascript console, you will have some tips about what was wrong, in the "Console" and/or in the "Network" tab by checking which requests as failed.

**Comment by josemvm** [comment]
@rldhont 
> When you've got this message, it means that one of the GetCapabilities requests (WMS, WFS, WMTS) or all has failed.

in this when i deactivate de first map theme the map loads with all layers and without problems

@Gustry this is what i can get in my javascript console:

imagem

**Comment by josemvm** [comment]
in the network tab everything looks good to me but i can provide an url if you want to investigate

thanks

**Comment by rldhont** [comment]
@Gustry I have apply https://github.com/3liz/lizmap-web-client/pull/4565

**Review by Gustry — APPROVED** [review]
I'm not able to review too much this PR, but given the fact it fixes tests on QGIS 3.34, LGTM.

You will have some conflicts while backporting, at least on 3.7 I think.

I think it's a blocker for releasing 3.7 and 3.8 this PR.

**Pull request merged**
