### PR TITLE
e2e: fix test

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by mind84** [comment]
Hi @nboisteault,

I cannot figured out why the click doesn't fire. so I've replaced the `click` with `focus` + `enter` key and seems to work.

Something like 

```js
        await page.locator('#jforms_view_edition__submit_submit').focus();
        await page.keyboard.press('Enter');
```

Could you try?

This change is included in this PR https://github.com/3liz/lizmap-web-client/pull/4635 but I could undo the change so we can use this PR to keep things organized.

Let me know

Thanks!

**Comment by nboisteault** [comment]
@mind84 I think this is due to the BS5 tooltips behavior that has change. I'll take a look.

**Comment by nboisteault** [comment]
I merged [this commit](767279d2c4009c849f08d23a8dac91375cbbdf6f) to put tooltip behavior aside.
I'm closing this PR.

**Comment by mind84** [comment]
> can you modify them in order to fix this issue

Yes

**Comment by Gustry** [comment]
Yes, I already notice that in some tests, we are adding data, but then, we do not remove or clean the dataset.
Some tests can't be launched twice.

Something we need to keep in mind.

Thanks for debugging.

**Comment by nboisteault** [comment]
Maybe `load_sql.sh` has to be run in an `afterEach` for tests modifying data.

**Comment by mind84** [comment]
@Gustry @nboisteault 

this https://github.com/3liz/lizmap-web-client/pull/4775 is probably enough to solve the n_to_m_relations e2e test issue.
 
I'll do a PR later to make the n_to_m_relations tests independent

Thanks

**Pull request closed without merging**
