### PR TITLE
Show Lizmap modules infos

### PR DESCRIPTION
**Pull request by nworr**
Funded by 3Liz
image

### CODE REVIEW

**Comment by mdouchin** [comment]
Can you please copy/paste here the list of modules returned by the page ? I would like to identify which ones we should hide (not relevant for the admin)

**Comment by Gustry** [comment]
@mdouchin I think it's the hardcoded list in the PR in `lizmap/modules/admin/lib/ModulesInfo/ModulesChecker.php`.

I can try to implement it in the JSON metadata, using your branch @nworr

**Comment by nworr** [comment]
| module |
|----|
 | jelix|
 |  jacl2|
  |  jacl2db|
|    jcommunity|
 |    admin|
 |  dataviz|
|        filter|
|        action|
  |      dynamicLayers|
 |       lizmap|
  |    proj4php|
  |     view|
   |    jacl2db_admin|
   |    jauthdb_admin|
   |    master_admin|

**Comment by Gustry** [comment]
@nworr I have rebased, and work on your branch, to include the JSON as well.

I can confirm, only `lizmapdemo` is in the output when we do not ask for `core` modules, which is fine for me.

**Comment by Gustry** [comment]
image

image

**Comment by Gustry** [comment]
I can't ask the review to @nworr as you are the author of the PR.
Can you check it @nworr and @mdouchin ?

**Review by mdouchin — APPROVED** [review]

**Pull request merged**
