### PR TITLE
Feature : element to go to given coordinates

### LINKED ISSUE #268: zoom to coordinates in the search box
i supose that's possible to search with Google (API) by geographic coordinate system... but not (yet)...

### LINKED ISSUE #1232: Search by coordinates with OpenStreetMap
Hi everyone,

is it possible to set the search by address with the "internal" service of OpenStreetMap and not Nominatim?
I need to set the search by coordinates.

Thank you all.
Giorgio

### PR DESCRIPTION
**Pull request by nboisteault**
Funded by [DEAL Mayotte](http://www.mayotte.gouv.fr/Services-de-l-Etat/Direction-de-l-Environnement-de-l-Amenagement-et-du-Logement-DEAL).

Custom element to let user zoom or center to given latitude/longitude.

Fix #1232 
Fix #268 

go-to-coordinates

### CODE REVIEW

**Comment by Gustry** [comment]
My review is quite limited on CSS/Javascript :)
I can review a GIF :p

**Comment by nboisteault** [comment]
@Gustry i should have pinged you instead :) GIF added !

**Review by rldhont — APPROVED** [review]

**Review by rldhont — CHANGES_REQUESTED** [review]
Can you update the changelog ?

**Comment by mdouchin** [comment]
Nice feature. What about find a way to not show the search input at startup, but only when the user clicks on a button ? To keep the UI thin and simple ?

**Comment by nboisteault** [comment]
@mdouchin : something like that ? The top array open the overview as usual, the bottom array toggle go-to-coordinates element.
image

**Comment by josemvm** [comment]
is it possible to choose an avaiable CRS project?

**Comment by josemvm** [comment]
something like this:

imagem

**Comment by josemvm** [comment]
@nboisteault IMHO it needs a small highlighted circle at the target imagem

**Comment by rldhont** [comment]
@nboisteault I think it needs a small highlighted circle at the target

**Comment by nboisteault** [comment]
> @nboisteault I think it needs a small highlighted circle at the target

@rldhont  How this circle is hidden when users don't it want anymore? A button which toggle visibility? A timeout?

**Comment by josemvm** [comment]
with imagem
:-)

**Comment by nboisteault** [comment]
[New PR taking care of given comments.](https://github.com/3liz/lizmap-web-client/pull/1827)

**Pull request closed without merging**
