### PR TITLE
add postgresql geography type to geometryDatatypeMap

### PR DESCRIPTION
**Pull request by flobz**
## Description

This change allow to edit postgres geography column on lizmap.

### CODE REVIEW

**Comment by nboisteault** [comment]
@rldhont @mdouchin ok to merge?

**Comment by rldhont** [comment]
@nboisteault not yet.

@flobz can you apply php-cs-fixer ?

**Review by rldhont — CHANGES_REQUESTED** [review]
does this change really allow to edit postgres geography column on lizmap ?

Lizmap only uses `ST_GeomFromText`, to edit geography, Lizmap also needs `ST_GeogFromText`  or convertion form geometry to geography.

**Comment by flobz** [comment]
> does this change really allow to edit postgres geography column on lizmap ?
> 
> Lizmap only uses `ST_GeomFromText`, to edit geography, Lizmap also needs `ST_GeogFromText` or convertion form geometry to geography.



> does this change really allow to edit postgres geography column on lizmap ?
> 
> Lizmap only uses `ST_GeomFromText`, to edit geography, Lizmap also needs `ST_GeogFromText` or convertion form geometry to geography.

On my server I have tested:

- create new point on map
- edit point
- delete point

It seems to work well...

**Comment by nboisteault** [comment]
@rldhont I suggest waiting lizmap 3.5 as we have freezed Lizmap 3.4.

**Comment by mdouchin** [comment]
This change seems minor. I do not think it will harm Lizmap Web Client for 99% of people not using geography type. I think we can merge in master ?

**Review by rldhont — APPROVED** [review]
Can be merged in master

**Review by mdouchin — APPROVED** [review]

**Pull request merged**
