### PR TITLE
[BUGFIX] small graphical details between LWC desktop mode and mobile mode

### LINKED ISSUE #701: small graphical details between LWC desktop mode and mobile mode
hi,

I found some small graphical details:

**mobile mode:**

- the "Login" header truncates and overlaps the logo:
image1
-  the "Administration" header overlaps the logo and once inside the administration menu, the strings for the logged user/"admin" and "Projects" have a different char font:
image2
- there's an empty space on left in the headers (Administration/image above, Main and Projects)
image3
proj

inside the map project the header it's ok:
ok

**desktop mode:**
- after login, drop down menu - behavior ok:
login1
- after login, inside the Administration menu/My account - different char font:
logadmi
-  **(master branch, after commit https://github.com/3liz/lizmap-web-client/commit/b83f1a59f119b8804e87b3ee5d0fbd10d2648dde)** inside the map project, after login - this behavior, 
lll

thanks in advance for your attention

### PR DESCRIPTION
**Pull request by rldhont**
Fixed #701

### CODE REVIEW

**Comment by rldhont** [comment]
@mdouchin @josemvm this PR fixed #701, are you agree with these changes ?

**Comment by josemvm** [comment]
hi @rldhont 


in 
>lizmap/www/css/media.css

the
`padding-right: 20px;`

is needed to prevent trunks on the right:
imagem


for the purpose of homogenizing, it's possible to remove the bold for the "**user-login**" here:

> lizmap-web-client/lizmap/modules/view/templates/main.tpl

`<b id="info-user-login" class="text">{$user->login|eschtml}</b>`

but not for the "**Projects**" here:

>  lizmap-web-client/lizmap/var/themes/default/jauth/index.tpl

`<span class="text"><b>{@view~default.repository.list.title@}</b></span>`

i don't know where...

**Comment by rldhont** [comment]
Ok I'll checkout the padding-right
And I removed the bold.

**Comment by rldhont** [comment]
@josemvm and @mdouchin I have updated the commit!

**Pull request merged**
