### PR TITLE
Use white icons on button.btn-primary class hover

### PR DESCRIPTION
**Pull request by ygorigor**
Change icons color on hover over buttons with btn-primary class

Without this commit
without_commit

With this commit
with_commit

### CODE REVIEW

**Comment by rldhont** [comment]
@ygorigor do the changes need to be backported ?

**Comment by ygorigor** [comment]
> @ygorigor do the changes need to be backported ?

Yes. At least to 3.5 and 3.4

**Comment by nboisteault** [comment]
@ygorigor could you make two gifs, one with previous behavior and one with new behavior ?

**Comment by ygorigor** [comment]
> @ygorigor could you make two gifs, one with previous behavior and one with new behavior ?

Done @nboisteault. Look in commit description

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
thanks @ygorigor

**Review by drillinP — APPROVED** [review]

**Review by nboisteault — APPROVED** [review]

**Comment by nboisteault** [comment]
Thanks @ygorigor !

**Comment by ygorigor** [comment]
> Thanks @ygorigor !

You welcome

**Pull request merged**
