### PR TITLE
Patch filter

### PR DESCRIPTION
**Pull request by nboisteault**
This fixes a bug @pcav wrote about in lizmap mailing list the 31/01/2020.

### CODE REVIEW

**Comment by rldhont** [comment]
This issue does not exist in 3.2 ?

**Comment by nboisteault** [comment]
Filter has been introduced in 3.3 isn't it ?

**Comment by nboisteault** [comment]
@pcav can you test this PR on your project ? Thanks

**Comment by rldhont** [comment]
> Filter has been introduced in 3.3 isn't it ?

Yes, you're right

**Comment by pcav** [comment]
Will do ASAP, thanks!
What is the best way to test?

**Comment by nboisteault** [comment]
With git : 
`git checkout -b nboisteault-patch-filter release_3_3`
`git pull https://github.com/nboisteault/lizmap-web-client.git patch-filter`

**Comment by pcav** [comment]
The filter by country name seems fixed, the numeric filters still do not show up.
Is replacing the filters.js file enough for testing?
Thanks.

**Comment by nboisteault** [comment]
As I just changed `filter.js` in this commit, yes it is enough. Numeric filters have to be fixed server side.

**Comment by pcav** [comment]
Oh, I see. So what about disabling them for others in the plugin @Gustry , or at least give a warning?

**Comment by rldhont** [comment]
@pcav if lizmap has 2 differents issues, it will be great to have 2 description in github/lizmap-web-client/issues and to PR to fix them.

**Comment by pcav** [comment]
OK, will open a ticket for the numeric filters. Sorry I cannot be timely, now on intensive training

**Comment by Gustry** [comment]
> Oh, I see. So what about disabling them for others in the plugin @Gustry , or at least give a warning?

Sure, it's usually what the plugin does.

According to the documentation:
https://docs.lizmap.com/next/en/publish/lizmap_plugin/form_filtering.html

> It works only for database layers: PostgreSQL (recommended), Spatialite and GeoPackage

So it should work with your GPKG too according to the doc

**Pull request merged**
