### PR TITLE
Try QGIS Server if lizmap server plugin error

### PR DESCRIPTION
**Pull request by rldhont**
Try QGIS Server with WMS GetCapabilities Without MPA only if lizmap plugin is not well installed or configured.

Funded by 3Liz

### CODE REVIEW

**Review by mdouchin — APPROVED** [review]

**Review by Gustry — APPROVED** [review]
I have removed cypress related lines.

LGTM

**Comment by rldhont** [comment]
Thanks @Gustry

**Comment by dmarteau** [comment]
LGTM for the functonal (I did not check for the code). 

However, I wish  that could be improved on the future by implementing a proper healthcheck url for Qgis server.

**Review by dmarteau — APPROVED** [review]

**Comment by dmarteau** [comment]
Don't forget that bare Qgis server return an error 500 if you don't give a `MAP`: this is not really relevant for for good healthcheck/presence test.

**Comment by rldhont** [comment]
> Don't forget that bare Qgis server return an error 500 if you don't give a `MAP`: this is not really relevant for for good healthcheck/presence test.

This is why it is done only if lizmap plugin is not installed or well configured.

**Pull request merged**
