### PR TITLE
quick fix using is_array

### PR DESCRIPTION
**Pull request by nworr**
no more php error in php8
 

Ticket : #3154

### CODE REVIEW

**Review by mdouchin — APPROVED** [review]
Thanks a lot. Ok for this fix, but we should in the future better understand why this `self::$qgisEdittypeMap` could return something else ;)

**Review by laurentj — CHANGES_REQUESTED** [review]
There is the issue because `$this->fieldEditType` is `List` and we don't support `List` into `$qgisEdittypeMap`. So the test should check first that `self::$qgisEdittypeMap[$this->fieldEditType]` exists before checking the `readonly` parameter.

**Review by laurentj — APPROVED** [review]
r+

**Comment by nworr** [comment]
question before merging, 
- are the (backport release) labels correct ?
- need to add a new feature to report unhandled fieldEditType ?

**Pull request merged**
