### PR TITLE
Lint - Introduce stylelint for CSS files

### PR DESCRIPTION
**Pull request by Gustry**
Introduce https://stylelint.io/ for checking CSS files.

These were just automatically fixed by the tool. I had to disable a few `"rules"` for now in the configuration file.
I'm happy to discuss these with CSS maintainers.

This is part of an going effort "basic" checks on files (PHP, JS...)

### CODE REVIEW

**Comment by Gustry** [comment]
@nboisteault or @mind84 I'm keen to have feedbacks, if it's this relevant or not, etc.

I had to disable some rules, because they are too many for now.
At this stage, there are no lines reported when launching the CLI.

**Comment by mind84** [comment]
Hi @Gustry!

Nice addition! 

I see no reason to not get support from this tool. I think we can discuss about the configuration and which rules to add or to remove. In general I don't have any strong opinion on CSS, if it works it's ok and I forget about it :smiley:, so this tool could help me and others "CSS lazy people" a lot .

How you plan to insert this tool in the PR validation workflow?

**Review by nboisteault — APPROVED** [review]

**Comment by Gustry** [comment]
Should we backport this to all active branch ?

> How you plan to insert this tool in the PR validation workflow?

Yes @mind84 it's on the way. There is a `pre-commit` config file at the root of the git repository. It's to integrate step by step all CI checks : PHP, JS, CSS, Lint, etc
There is a GitHub action coming about StyleLint

**Comment by Gustry** [comment]
We also need to check these rules which are currently disabled. It was just to make the CLI happy @nboisteault and @mind84

**Pull request merged**
