### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by rldhont**
Branch for the refactoring from @alagroy-42

### CODE REVIEW

**Comment by rldhont** [comment]
https://github.com/3liz/lizmap-web-client/pull/2060 needs to me merge before

**Comment by rldhont** [comment]
Thanks @alagroy-42 

I am waiting for @nboisteault feedbacks.

**Comment by nboisteault** [comment]
@rldhont I did let @alagroy-42 test. So @alagroy-42 you can merge when all tests are green.

**Review by alagroy-42 — APPROVED** [review]

**Review by nboisteault — APPROVED** [review]
Let's merge! :)

**Comment by ygorigor** [comment]
@alagroy-42 after this commit all dataviz plots are gone

**Comment by rldhont** [comment]
@ygorigor can you open an issue

**Pull request merged**
