### PR TITLE
Reorganize configuration pages

### PR DESCRIPTION
**Pull request by laurentj**
- Parameters in the form for the configuration, are grouped by domain.
- Setup of projects/repositories are moved to a separate page.

The goal of these changes are to ease to configure lizmap. The previous configuration page was too heavy, and parameters were in a random order.

Refs #870

### CODE REVIEW

**Comment by ygorigor** [comment]
@laurentj I merged this changes, and I lost Save button when editing configuration. 
image

Can you check if this is only for me?
Thanks

**Comment by rldhont** [comment]
@ygorigor can you open an issue ?
You request will be more effective than here in this closed pull request, thanks.

**Comment by ygorigor** [comment]
@rldhont I'm not sure if this is an general issue, or only in my case

**Comment by nboisteault** [comment]
@ygorigor I have the same issue. Please open an issue.

**Comment by laurentj** [comment]
@ygorigor bug fixed. Thanks for your report

**Pull request merged**
