### PR TITLE
Feature : component to display mouse position or center to given coordinates

### LINKED ISSUE #268: zoom to coordinates in the search box
i supose that's possible to search with Google (API) by geographic coordinate system... but not (yet)...

### LINKED ISSUE #1232: Search by coordinates with OpenStreetMap
Hi everyone,

is it possible to set the search by address with the "internal" service of OpenStreetMap and not Nominatim?
I need to set the search by coordinates.

Thank you all.
Giorgio

### PR DESCRIPTION
**Pull request by nboisteault**
Funded by [DEAL Mayotte](http://www.mayotte.gouv.fr/Services-de-l-Etat/Direction-de-l-Environnement-de-l-Amenagement-et-du-Logement-DEAL).

Custom element displaying mouse position or let user center to given latitude/longitude in different projections. (Like in QGIS)

Fix #1232 
Fix #268

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by nboisteault** [comment]
@mdouchin : how to handle 'degree minute' unit with edition as it add some symbols? I would say edition is enabled only with other 'simple' units.

image

**Comment by mdouchin** [comment]
I agree: no need to let the user enter `43°34'67''` -> the user will only be able to use simple real numbers

**Comment by nboisteault** [comment]
@rldhont @josemvm : concerning [this comment](https://github.com/3liz/lizmap-web-client/pull/1816#issuecomment-694826430), this button is only available if address search is active. We then need something else.

**Comment by josemvm** [comment]
@nboisteault is it possible for you (or something like this)? 

imagem

thanks for your work!

**Comment by nboisteault** [comment]
@mdouchin @rldhont Actually when mouse is out of the map we display a text instead of last coordinates. Should i keep this behavior? I'd prefer to keep that coordinates as it can be handy for users to write their own coordinates based on those.

**Comment by nboisteault** [comment]
@mdouchin @rldhont It is ready. Please test exhaustively with different projections.

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
new approval

**Review by mdouchin — APPROVED** [review]

**Comment by josemvm** [comment]
@nboisteault 
>component to display mouse position

does this mean that the user can also read coordinates on different projection systems?

**Pull request merged**
