### PR TITLE
[Enhancement] Refactoring edition controller

### PR DESCRIPTION
**Pull request by rldhont**

### CODE REVIEW

**Comment by rldhont** [comment]
@josemvm @jonnyforestGIS can you test this branch ? No new features, just code enhancement.
Thanks

**Comment by josemvm** [comment]
hi @rldhont 

i'll test it asap

**Comment by jonnyforestGIS** [comment]
hi @rldhont. I will test. And give feedback

**Comment by josemvm** [comment]
when you load map and when you try to edit:

`
2017-10-19 13:09:02     10.27.3.8       error   2017-10-19 13:09:02     [0]     syntax error, unexpected 'public' (T_PUBLIC)    /var/www/html/liz-smpc/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php    534`

**Comment by jonnyforestGIS** [comment]
So in my case:
I create a dummy project with a empty Postgis layer.
Loads fine:
When i select de layer to edition and add the buttons of edition freeze and the progress bar still animated and don't let edit.
When i Open the Chrome Developer Tools i have this error:

`GET http://localhost/testing/index.php/lizmap/edition/createFeature?repository=intranet&project=test_lizmap&layerId=areas_interesse20171019121832370&featureId= 500 (Internal Server Error)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getEditionForm @ edition.js:498
launchEdition @ edition.js:464
(anonymous) @ edition.js:348
dispatch @ jquery-1.12.4.min.js:3
r.handle @ jquery-1.12.4.min.js:3`

**Comment by rldhont** [comment]
@josemvm and @jonnyforestGIS Thanks, I have rebased the branch. Recreate the branch to test it locally.

**Comment by rldhont** [comment]
@josemvm @jonnyforestGIS @gioman ExternalResource support!

**Comment by jonnyforestGIS** [comment]
Nice :) 👍 amazing

**Comment by josemvm** [comment]
http://changelog.kartoza.com/en/entry/453

**Comment by rldhont** [comment]
@josemvm I am working on it, a first step will be added to this PR.

**Comment by rldhont** [comment]
@josemvm what do you mean by pointing to this link http://changelog.kartoza.com/en/entry/453 ?

**Comment by josemvm** [comment]
hi @rldhont 
just to illustrate this important feature. go ahead!

**Comment by jonnyforestGIS** [comment]
@rldhont [Off-topic]: Can you accept the pull request of documentation i'm doing some changing and fix some minor bugs

**Comment by josemvm** [comment]
hi @rldhont 

i have downloaded your branch https://github.com/rldhont/lizmap-web-client/tree/master-edition-32

- at map loading i have some php warnings in `error.log`:

`2017-12-01 01:00:53     10.80.0.6       warning 2017-12-01 01:00:53     [2]     touch(): Utime failed: Operation not permitted/var/www/html/lizmap-web-client-master-edition-32/lib/jelix-plugins/cache/file/file.cache.php    189`

`2017-12-01 01:00:53     10.80.0.6       warning 2017-12-01 01:00:53     [2]     touch(): Utime failed: Operation not permitted/var/www/html/lizmap-web-client-master-edition-32/lib/jelix-plugins/cache/file/file.cache.php    189`

`2017-12-01 01:00:53     10.80.0.6       warning 2017-12-01 01:00:53     [2]     touch(): Utime failed: Operation not permitted/var/www/html/lizmap-web-client-master-edition-32/lib/jelix-plugins/cache/file/file.cache.php    189`

- when i try to save a new feature by edition form it's not possible and i have these php notices in `error.log`:

`2017-12-01 01:01:19     10.80.0.6       notice  2017-12-01 01:01:19     [8]     Undefined property: qgisVectorLayer::$geometryType     /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       221`

`2017-12-01 01:01:19     10.80.0.6       notice  2017-12-01 01:01:19     [8]     Undefined property: qgisVectorLayer::$geometryType     /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       221`

`2017-12-01 01:01:33     10.80.0.6       notice  2017-12-01 01:01:33     [8]     Undefined property: qgisVectorLayer::$geometryType     /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       221`

`2017-12-01 01:01:33     10.80.0.6       notice  2017-12-01 01:01:33     [8]     Undefined property: qgisForm::$geometryColumn /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisForm.class.php       433`

`2017-12-01 01:01:33     10.80.0.6       notice  2017-12-01 01:01:33     [8]     Undefined property: qgisVectorLayer::$geometryType     /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       221`

thanks one more time for these new features!

**Comment by rldhont** [comment]
HI @josemvm ,
Thanks for the review!

The first error, at map loading, is due to file rights in cache. You have to update owner of the cache folder. https://stackoverflow.com/questions/1676743/why-would-file-put-contents-succeed-but-touch-fail

**Comment by rldhont** [comment]
@josemvm the last commit 0d87433 fixed the errors in edition

**Comment by josemvm** [comment]
sorry for the `The first error`...

the form doesn't close after saving:

`2017-12-01 10:20:45     10.80.0.6       warning 2017-12-01 10:20:45     [2]     Invalid argument supplied for foreach() /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php    415`

**Comment by rldhont** [comment]
@josemvm more logs ?

**Comment by josemvm** [comment]
@rldhont no more logs...

the same behavior and the same php warning for all options form (close form, create new feature and reopen form).

the feature is created or updated but the form always remains filled with last data

**Comment by josemvm** [comment]
sorry...

after feature updated:

`2017-12-01` 17:50:16     10.27.11.245    notice  2017-12-01 17:50:16     [8]     Undefined variable: dbField     /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       472`

`2017-12-01 17:50:16     10.27.11.245    notice  2017-12-01 17:50:16     [8]     Trying to get property of non-object    /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       475`

`2017-12-01 17:50:16     10.27.11.245    warning 2017-12-01 17:50:16     [2]     Invalid argument supplied for foreach() /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       510`

`2017-12-01 17:50:16     10.27.11.245    notice  2017-12-01 17:50:16     [8]     Undefined variable: pkVals      /var/www/html/lizmap-web-client-master-edition-32/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php       531`

**Comment by rldhont** [comment]
the error is provided by the SQL request, if you don't have more logs, I hope that @mdouchin will test and fix it.

**Comment by josemvm** [comment]
a first small note: the `Manage point coordinates` appears for all geometry types and not only for points geometry...

**Comment by rldhont** [comment]
Thanks @josemvm it's usefull

**Comment by rldhont** [comment]
You can Manage all the points you add to the geometries not only for point.
It will be used for create geometry based on Geolocation.

**Comment by josemvm** [comment]
is the last commit (`Fix qgisVectorLayer dataFields`) to fix the `form always remains filled with last data`?

> You can Manage all the points you add to the geometries not only for point.
It will be used for create geometry based on Geolocation.

very nice :-)

**Comment by mdouchin** [comment]
We should perhaps use the word "node" instead of point for geometries wich are not point

* Point : Manage point coordinates
* Other types : Manage (next ?) node coordinates

**Comment by josemvm** [comment]
`Other types : Manage (next ?) node coordinates`

vertex instead node(?)...

>vertex 
[Euclidean geometry] One of a set of ordered x,y coordinate pairs that defines the shape of a line or polygon feature.

**Comment by rldhont** [comment]
@josemvm the last commit 9b7637381bd85d315af4d98c532a7670c14a320d `Fix qgisVectorLayer dataFields` is about to fix the errors you provide after update data.

**Comment by josemvm** [comment]
hi @rldhont 

i can´t create a new branch for this commit https://github.com/3liz/lizmap-web-client/pull/693/commits/ecc640dd6071756079291a3d794b6788fa744526

the `linked to geolocation` string needs translation, something like this:
`{@view~edition.point.coord.option.geolocation.label@}`

i'll do some tests on new editing features

nice work, great!
thanks

**Comment by rldhont** [comment]
@josemvm I have fix the locales: point/vertex and geolocation and the issue with PG Feature insert and update with close form 10ac1116bbf7bfbc4cd067b23adc8e719004b129

**Comment by jancelin** [comment]
@rldhont, the last commit works well for closing, new object and reopen the form.
however, when I activate "create a new object" or "reopen the form", and if I don't create a point/polygon/line manually or by localization, then the form freeze  instead of telling me "you can't save this object without geometry".

I still have the drop-down menus not active graphically. In the version 3liz/lizmap-web-client/master no problem, it's when I apply your Pull Request that it disappears.

**Comment by rldhont** [comment]
Hi @jancelin thanks for your feedback.

About the drop-don menus, what is the QGIS edition tool used to defined it ?

**Comment by josemvm** [comment]
hi @rldhont 

it's works fine for me!

i can't reproduce @jancelin issue

> however, when I activate "create a new object" or "reopen the form", and if I don't create a point/polygon/line manually or by localization, then the form freeze instead of telling me "you can't save this object without geometry".

after your last commits i noticed a significant delay when the user toggles between different CRS...,  the values of the coordinates are not updated immediately, the process is instantaneous if the user unchecks the `linked to geolocation`, selects the new CRS and checks again the `linked to geolocation`, but no problem...

**mobile mode:**
when the user try to `Add `feature from `Edition `tool the form doesn't appear, it's necessary to click again on the `Edition `tool and the same behavior for all options `After saved` (the form doesn't appear)

**Comment by jancelin** [comment]
I use relational values.
 I  tested with the value lists and this function works.

**Comment by jancelin** [comment]
The remodel function does not seem to work, if the operation is identical to Qgis. the other three work.
Always on Postgresql layers

**Comment by josemvm** [comment]
@jancelin is this the same?
 https://github.com/3liz/lizmap-web-client/issues/160
`how can we finish the reshaped feature?`

`probably, it needs double click to finish the reshape instead of a right click (as it happens in qgis desktop)...`

**Comment by josemvm** [comment]
if we are working with related tables and if child form is open, for close the edition the user needs to cancel the sub form, cancel the main form and at the end close the edition

i thing that the close edition button could do this set of operations...

**Comment by jancelin** [comment]
@josemvm is the same, Right click for Qgis, but I can't on lizmap. And the double click don't work for finish.

**Comment by josemvm** [comment]
oh... unfortunately :(

**Comment by josemvm** [comment]
**related table**s - when the user create a new feature in main table and chose the `Reopen form` `After saved` the form controller could detect if there are a child tables and show the possibility of `create a child` feature
imagem

thanks

**Comment by rldhont** [comment]
@mdouchin, @josemvm and @jancelin are you OK for merging ?

**Comment by josemvm** [comment]
excuse me @rldhont, have you solution for the reshape feature problem?

**Comment by rldhont** [comment]
I don't know why the double-click doesn't work fine.

**Comment by josemvm** [comment]
and the fix for (?)

> mobile mode:
when the user try to Addfeature from Editiontool the form doesn't appear, it's necessary to click again on the Editiontool and the same behavior for all options After saved (the form doesn't appear)

**Comment by rldhont** [comment]
My solution will be to add edition tool in geolocation dock.

**Comment by josemvm** [comment]
ok, for me, go ahead! the improvements will not end here 👍

**Comment by jancelin** [comment]
Almost OK, there remains the disappearance of the drop-down menus (relational value) which is blocking for me.
Do you have the same problem? or is it from me?
I don't have the problem with the current master version.

**Comment by josemvm** [comment]
@jancelin are you talking about `Value Relation` edit widget? i have not yet tried...

@rldhont the `File Name` and `Photo` edit widget doesn't appear

**Comment by jancelin** [comment]
@josemvm, yes, I'm talking about Value Relation edit widget.
 And there is a problem with the file/photo. similarly looking problem

**Comment by josemvm** [comment]
the same for `External Resource` edit widget

**Comment by rldhont** [comment]
I think I can merge and enhance for mobile after. What do you think @josemvm @jancelin @mdouchin ?

**Comment by jancelin** [comment]
OK for me

**Comment by josemvm** [comment]
hi @rldhont 

fixed 👍 go ahead!

**Pull request merged**
