### PR TITLE
Fix visibility of some controllers methods

### PR DESCRIPTION
**Pull request by laurentj**
Some methods are not supposed to be called from a browser,
but are called only from other controllers methods. So they
must not be public.

### CODE REVIEW

**Comment by laurentj** [comment]
There are other methods inside lizmap~service which seem to be protected theorically: all Get* methods called from the index method. Should we keep public or not?

**Comment by rldhont** [comment]
@laurentj you're right, except getProjectConfig the other Get* methods has to be protected

**Comment by laurentj** [comment]
Ok, why not. But why do not create urls for each get*, instead of having a parameter for index() ?

**Comment by rldhont** [comment]
Because each method matches OGC Service - Request parameters pair. These method are for convenience and has to be ported to the classes lizmap*Request.

**Pull request merged**
