### PR TITLE
[end2end] cors and projet filename test converted from cypress to playwright

### PR DESCRIPTION
**Pull request by nworr**
Tests converted using https://ray.run/tools/cypress-to-playwright and improved a bit
 
Funded by 3Liz

### CODE REVIEW

**Comment by nworr** [comment]
i created a dedicated en2end config to ignore `cors` test that can only be performed locally

**Review by Gustry — APPROVED** [review]
LGTM, as I don't review JS too much :)
But for the tests side, thanks.

**Comment by nworr** [comment]
> LGTM, as I don't review JS too much :) But for the tests side, thanks.

i set you as reviewer for the worflow side :)

**Review by nboisteault — APPROVED** [review]
Thanks @nworr !

**Comment by Gustry** [comment]
> i set you as reviewer for the worflow side :)

Thanks, no worries, it's what I did !

**Pull request merged**
