### PR TITLE
Map menu UI more mobile friendly (hamburger menu)

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
@mdouchin We close dock and subdock in mobile context when zooming or changing opacity in sub-dock :  

- https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/assets/js/switcher-layers-actions.js#L406
- https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/assets/js/switcher-layers-actions.js#L481

I find this behavior annoying. I think we could maybe close sub-dock but not dock and even better close nothing imo. Thoughts?

**Comment by nboisteault** [comment]
@Gustry feel free to test this new UI ;)

**Comment by mdouchin** [comment]
Thanks for your work. A quick question : have you tested to run the lizMap.addDock() public method and check if the new item is correctly added in the mobile dock new interface ?

**Comment by nboisteault** [comment]
@mdouchin yes atlas is correctly added in Montpellier project.

**Review by rldhont — APPROVED** [review]

**Pull request merged**
