### PR TITLE
Editing - Fix the value relation widget with multiple text values on feature modification

### PR DESCRIPTION
**Pull request by mdouchin**
In the form widget, when:

* there is a `text` field configured with a "Value relation" widget, 
* with the option `allow multiple` activated
* using a `text` field in the referenced layer for the code checkbox

QGIS adds double quotes around the text values, such as `{"one_value", "second_value"}`.

We need to remove these double-quotes for setting correctly the corresponding checkboxes.

Cypress test added.

Funded by #3liz

### CODE REVIEW

**Review by nboisteault — APPROVED** [review]
I have not tested but it looks good!

**Comment by mdouchin** [comment]
@rldhont ok for merge ?

**Comment by rldhont** [comment]
@mdouchin after 3.4.8

**Comment by mdouchin** [comment]
up

**Review by rldhont — APPROVED** [review]

**Pull request merged**
