### PR TITLE
[Bugfix] Treeeview symbols not in scale

### PR DESCRIPTION
**Pull request by rldhont**
A class is added to the symbol li if the symbol is out of scope and the category is italic and greyed.

Capture d’écran 2024-05-24 à 10 15 20

Capture d’écran 2024-05-24 à 10 15 32

Funded by EPF Haut De France

### CODE REVIEW

**Comment by Gustry** [comment]
Do you mean for rules which have predefined scales, like this ?

image

**Comment by rldhont** [comment]
Yes @Gustry , how this is displayed in QGIS treeview ?

**Comment by Gustry** [comment]
By default, strictly no change...

Peek 2024-05-24 09-57

Only if you toggle this : 

image


Then it's very dynamic, but not related to scale range of the symbol, but only related to symbols drawn : 

Peek 2024-05-24 10-00

But your idea is good. I would make it italic and/or greyed, similar to layer scale visibility : 

image

**Comment by rldhont** [comment]
Thanks @Gustry .

I have updated the main comment with previews.

**Comment by rldhont** [comment]
@Gustry ready for review

**Pull request merged**
