### PR TITLE
[Backport release_3_4][Bugfix] Empty value in Jelix checkboxes 

### PR DESCRIPTION
**Pull request by Gustry**
Backport from #2856

### CODE REVIEW

**Comment by rldhont** [comment]
> #jforms_view_edition_boolean_nullable

Which tests failed ?

**Comment by rldhont** [comment]
The PR https://github.com/3liz/lizmap-web-client/pull/2863 fixes the cypress test `form_edition_all_field_type`

**Comment by rldhont** [comment]
@Gustry can you rebase and then test cypress ? #2863 has been merged

**Comment by Gustry** [comment]
C'est bon : https://github.com/Gustry/lizmap-web-client/runs/5673361686?check_suite_focus=true

**Pull request merged**
