### PR TITLE
Project - Add public method checkAclByUser for lizmap based API backend

### PR DESCRIPTION
**Pull request by mdouchin**

### CODE REVIEW

**Review by laurentj — APPROVED** [review]

**Comment by mdouchin** [comment]
@laurentj  What about merging into master ? It could still be usefull ?

**Comment by nboisteault** [comment]
@mdouchin @laurentj it is now or later! :)

**Comment by nboisteault** [comment]
@mdouchin @laurentj do I tag it for 3.5 ?

**Comment by mdouchin** [comment]
It is safe to merge

**Comment by nboisteault** [comment]
@mdouchin Ok merge.

**Pull request merged**
