### PR TITLE
New option to disable the automatic permalink

### PR DESCRIPTION
**Pull request by rldhont**
In the main section of the JSON, add a new option to enable the automatic permalink : automatic_permalink.

It will be enabled by default.

Linked to https://github.com/3liz/lizmap-plugin/pull/590

### CODE REVIEW

**Comment by Gustry** [comment]
> It will be enabled by default.

You mean "automatic permalink" will be enabled by default ? So it will be the reverse compared to the plugin ?

**Comment by rldhont** [comment]
> > It will be enabled by default.
> 
> You mean "automatic permalink" will be enabled by default ? So it will be the reverse compared to the plugin ?

I keep the LWC 3.7 fonctionnality

**Comment by nboisteault** [comment]
> > > It will be enabled by default.
> > 
> > 
> > You mean "automatic permalink" will be enabled by default ? So it will be the reverse compared to the plugin ?
> 
> I keep the LWC 3.7 fonctionnality

It could be disabled by default in LWC 3.8.

**Comment by Gustry** [comment]
> I keep the LWC 3.7 fonctionnality

We need to be consistent with the plugin so :) Which is not the case, or to define what happen if the key is not found.
So you consider if the key is not found or `True`, then the automatic permalink is done, right ?

> It could be disabled by default in LWC 3.8.

Well, if we want to change the default behavior, I think it's better to do it ASAP.

People are creating new projects. The more we wait, the more they will have to manually update their CFG file.

**Pull request merged**
