### PR TITLE
Docks refactoring with CSS flexbox

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by mdouchin** [comment]
Great ! Do you plan to also refactor the header ? There is some bootstrap old-school header, logo, auth stuff here, not really easy to override.

**Comment by nboisteault** [comment]
@rldhont Can you tell me a use case where updateMiniDockSize() was useful ? I'd like to see how I could remove it.

**Comment by rldhont** [comment]
`updateMiniDockSie()` has been coded to fix issue in height definition for locateByLayer, streetView JS plugin, etc.

**Comment by nboisteault** [comment]
> Great ! Do you plan to also refactor the header ? There is some bootstrap old-school header, logo, auth stuff here, not really easy to override.

I plan do it in another PR.

**Comment by nboisteault** [comment]
@laurentj @rldhont @mdouchin ready for review !

**Pull request merged**
