### PR TITLE
[Bugfix] PostgreSQL typname can be _text

### PR DESCRIPTION
**Pull request by rldhont**
Fix Undefined index: _text in /srv/lzm/lizmap/modules/lizmap/lib/Form/QgisFormControl.php 201

When jelix retrives PostgreSQL fields info, the jDbFieldProperties type value comes from pgtype.typname and can be _text for text.

Fixing https://paste.sh/wELXEssH#2sMuGK8X5c82wOu61oyv8Fbz

### CODE REVIEW

**Review by nboisteault — APPROVED** [review]

**Comment by mdouchin** [comment]
I think the `_text` type name fetched by Jelix is the representation of an array of text in PostgreSQL, `text[]`

See the query in the `pg_type` PostgreSQL system table:

```sql
SELECT typname, typinput, typoutput, typreceive FROM pg_type WHERE typname ILIKE '%text%';
```
Which returns

```
 typname | typinput | typoutput | typreceive 
---------+----------+-----------+------------
 text    | textin   | textout   | textrecv
 _text   | array_in | array_out | array_recv
```

Further test: when creating this table

```sql
CREATE TABLE test (name text, names text[]);
INSERT INTO test VALUES ('bob', ARRAY['bib']);
```

I can get the _text with the query

```sql
SELECT column_name, data_type, udt_name FROM information_schema.columns WHERE table_name = 'test';
```
which returns

```
 column_name | data_type | udt_name 
-------------+-----------+----------
 name        | text      | text
 names       | ARRAY     | _text
```

**Comment by nboisteault** [comment]
@mdouchin you're right I've added `'_int' => 'integer[]',` weeks ago so this PR should add `'_text' => 'text[]',`

**Comment by rldhont** [comment]
Thanks @nboisteault I have not take an intensive look to _int.

@drillinP Can you test this PR ? Thanks

**Comment by mdouchin** [comment]
The best thing to do would indeed to add more array casting, such as _bigint, _varchar , etc. and to have at least a unit test which checks the read & the write inside PostgreSQL arrays, depending on the field type (simple text input, value relation, relation widget, etc.)

**Review by drillinP — APPROVED** [review]

**Review by laurentj — APPROVED** [review]

**Pull request merged**
