### PR TITLE
Speed up FCP (first contentful paint)

### PR DESCRIPTION
**Pull request by nboisteault**
Speed up FCP (first contentful paint). This PR allows JavaScript scripts to be loaded after the HTML is loaded and parsed thanks to `defer` attribute. It is interesting for users with a slow connection, this way they will not wait too long with a blank page.

Funded by 3Liz

TODO:
- [x] https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/view/controllers/lizMap.classic.php#L489 ? Is it documented?

### CODE REVIEW

**Comment by rldhont** [comment]
@nboisteault can you add some description to this PR to explain how your speed up lizmap loading ?

**Review by rldhont — CHANGES_REQUESTED** [review]
Describe changes

**Comment by nboisteault** [comment]
> Describe changes

Done.

**Review by rldhont — APPROVED** [review]
Thanks

**Review by laurentj — APPROVED** [review]

**Pull request merged**
