### PR TITLE
GeolocationSurvey component for Permagro

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
I'll take care of translation later.

**Comment by nboisteault** [comment]
@mdouchin we'll need a last discussion about UI.

**Comment by nboisteault** [comment]
image

image

**Comment by nboisteault** [comment]
@rldhont @mdouchin @laurentj code ready for review !

**Comment by nboisteault** [comment]
@rldhont @mdouchin @laurentj is it ok to merge ? There are a lot of changes I'd like to have for my next developments.

**Comment by josemvm** [comment]
@nboisteault please can you revert the colors?
imagem

and, please, don't forget this improvement, this is basic and very very important for survey work!


thanks on more time 👍

**Comment by rldhont** [comment]
@josemvm which colors ?

The direction has not been funded.

**Comment by josemvm** [comment]
> which colors ?

lwc version 3.3 - all buttons are blue

geolocation tool
imagem

print tool
imagem

time magager
too

> The direction has not been funded

but the sponsor would be better served if he knew about this possibility and the lwc would be more enriched! :-)

**Pull request merged**
