### PR TITLE
[Bugfix] Popups - always remained active and minidock dimensions

### LINKED ISSUE #1068: popup - used once, allways remains activated
when you do a click on the map the popup displays the contents of features and highlights them like you can see as below:

imagem

after you close the popup window and select some features using any selection method/tool (case selection tool, by circle):

imagem

the last/previous highlighted geometries by popup come back to the map:

imagem

lizmap master and previous
qgis server 2.14 e 2.18

thanks

### PR DESCRIPTION
**Pull request by rldhont**
Fixed #1068 popup - used once, allways remains activated

In the same time, popup in minidock dimension #1065 is calculated after content added.

### CODE REVIEW

**Comment by josemvm** [comment]
hi @rldhont 
so, everything is OK, now, with popups!!!

however i think you can improve a little bit more:

when the user clicks on two or more very close features and chooses to edit one from the popup
imagem

the popup should be disabled and the feature one on edition should be marked as selected
imagem

thank you so much :-)

**Comment by nboisteault** [comment]
@josemvm Do you change something in Montpellier QGIS project to display the geometries ?

**Comment by nboisteault** [comment]
@josemvm forget my question, I had an issue on my side.

**Comment by nboisteault** [comment]
@rldhont with lizmap_3_2 I can not display geometries when clicking on it but the selection tool does not select.
With your patch it is the contrary, I can display geometries when clicking on it but the select tool does select.

**Comment by nboisteault** [comment]
@josemvm Can you open another issue for the enhancement you are suggesting please ?

**Pull request merged**
