### PR TITLE
Enhanced selection

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
@rldhont @mdouchin For the moment I refactored the code the new way. I'm now going to enhance the selection tool.

**Comment by Gustry** [comment]
Waiting for the GIF ;-)

**Comment by nboisteault** [comment]
> Waiting for the GIF ;-)

I have created some end2end tests with Cypress. I'll make a PR with it and an awesome GIF :)

**Comment by nboisteault** [comment]
@Gustry https://github.com/3liz/lizmap-web-client/pull/1553#issue-383507294

**Comment by rldhont** [comment]
@nboisteault thanks! waiting for the next step

**Comment by josemvm** [comment]
@nboisteault can you consider this possibility in your improvement? https://github.com/3liz/lizmap-web-client/issues/650

imagem

thanks!

**Comment by nboisteault** [comment]
Yes, we are going to make this feature.

**Comment by josemvm** [comment]
@nboisteault please take a look at https://github.com/3liz/lizmap-web-client/issues/690 and https://github.com/3liz/lizmap-web-client/issues/1221

**Comment by josemvm** [comment]
@nboisteault can you take a look here https://github.com/3liz/lizmap-web-client/issues/609

thanks for your great improvements on this tool 👍

**Comment by nboisteault** [comment]
Funded by http://www.le64.fr/accueil.html

**Pull request merged**
