### PR TITLE
Tests - Add helper to test if the map is OK when opening it

### PR DESCRIPTION
**Pull request by Gustry**
@nboisteault This kind of helper would have helped me a lot yesterday about #4386 or for @rldhont about #4393

If possible @nboisteault should we use **everywhere** this kind of helper to open a map ?

Sorry, I'm not a JS dev...
I know there is an error about playwright now

### CODE REVIEW

**Comment by Gustry** [comment]
> @Gustry this is not possible w/ playwright?

What do you mean ? As I wrote, I'm not a JS dev, and I first wanted the idea of this PR.
I was quoting this link in my PR : 
https://github.com/microsoft/playwright/issues/10358

**Comment by Gustry** [comment]
I kind of `gotoMap` to visit a map and check some basic requests such as `getCapabilities` or basic button in the interface.

**Comment by rldhont** [comment]
A try for playwright - to be generalized https://github.com/3liz/lizmap-web-client/pull/4451

**Comment by Gustry** [comment]
@rldhont @nboisteault I have rebased after the PR from @rldhont #4451 

I don't know how we can pass the flag for triggering a false positive test about the error.

I will merge this PR if OK for you. This work is be continued in a next step : 

* migrate all `gotoMap` for both cypress and playwright, like #4478
* Improve both function `gotoMap` to check WMS requests and avoid a wasted `wait` etc, because this will considerable slowdown tests when running them all otherwise
* Uncomment the false positiv test about invalid layer in both Cypress/playwright

Stoping on my side on this

**Pull request merged**
