### PR TITLE
fix HTTPS Nominatim URL

### LINKED ISSUE #858: OSM nominatim search problem - ?http / https ?
Search in my lizmap setup stopped working. (nominatim with OSM)
And so did the QuickFinder plugin in QGIS.
Was not able to search locations using nominatim.

**I was able to get Quickfinder working in QGIS desktop 
by setting a plugin service setting from http:// to https://**
I would have tried the same for lizmap - not able to figure out how ... :(

Any help appreciated

Lizmap setup i have, is not configured for SSL. Plain http used while viewing "lizmap" maps
Qgis2.18.18, lizmap3.2pre,php-7.2,Apache2.4.33

### PR DESCRIPTION
**Pull request by Gustry**
Fix #858 
fix HTTPS Nominatim URL

### CODE REVIEW

**Comment by nboisteault** [comment]
I've tested, it works. Thanks a lot !

**Comment by rldhont** [comment]
@Gustry I'll cherry-pick your commit in release_3_0 then merge branches form 3_0 to 3_1 to 3_2 to master to fix the issue.

**Comment by Gustry** [comment]
Ok thanks

**Comment by rldhont** [comment]
Manually merged

**Pull request closed without merging**
