### PR TITLE
[Bugfix] Assert $layer exists

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
@rldhont This commit has to be made in the same file but in another path in release_3_4. How do I do the backport?

**Comment by rldhont** [comment]
@nboisteault Once this PR merged, you can opne a new one for release_3_4 with _manually backport #2092_ as description

**Review by rldhont — APPROVED** [review]

**Comment by Gustry** [comment]
I'm not a PHP dev, but it seems these 70 edited lines could be replaced by 3 lines ?
```php
if (!$layer) {
    return array();
}
```
?
IMHO, it's better visibility :
* keeping our code to the left side with not too much indentation
* exiting from the code as soon as we can

Sorry for the noise if I'm wrong, just trying to read the PR :)

**Comment by rldhont** [comment]
@Gustry you are right
```php
if (!$layer) {
    return $result;
}
```
this code could have been used

**Pull request merged**
