### PR TITLE
Cypress ci fix

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
@Gustry I have tried the backport bot but it failed. There is this message here : 
`Warning: Unexpected input(s) 'bot_token_key', valid inputs are ['bot_username', 'bot_token', 'github_token']`
It is weird as `bot_token_key` is in this action doc.
Did you test to backport manually as written above?

**Comment by Gustry** [comment]
I have tried, no error indeed. Sad ...

I think you can skip this warning.

**Comment by Gustry** [comment]
Ok, the error is another part, CF logs.

**Comment by Gustry** [comment]
I think your issue is due to the update of a workflow file **within** this PR.
For security reason, updating a workflow file with a token require a special token scope, and the bot 3liz-bot hasn't this scope in its token.

Let's check if it's the reason with another pull request that will be backported. So I won't update the token because this PR is quite a special use-case.

I will backport this PR manually.

**Pull request merged**
