### PR TITLE
JS Map - Use native zoom levels

### PR DESCRIPTION
**Pull request by rldhont**
For EPSG:3857 and others if only 2 scales are defined, the native zoom levels are used for the Map.

Some legacy codes are removed.

FUnded by 3Liz

### CODE REVIEW

**Comment by Gustry** [comment]
As discussed together about the print, [KISS](https://fr.wikipedia.org/wiki/Principe_KISS) : same projection everywhere ?

Linked to PR https://github.com/3liz/lizmap-plugin/pull/526

**Comment by Gustry** [comment]
Trying to sum up the conversation from yesterday : 

version <= 3.6 : 
* nothing changed
* CFG configuration like existing
* ```json
         use_native_scales: false, 
        "mapScales": [
            100,
            500,
            1000,
            2500,
            5000,
            10000,
            25000,
            50000,
            100000,
            250000,
            500000
        ],
        "minScale": 100,
        "maxScale": 500000,
    ```

![image](https://github.com/3liz/lizmap-web-client/assets/1609292/e5ca571c-f424-4784-bbb7-28b5ad9e99b9)


Version >= 3.7

* checkbox "Use native".
* If checked : 
  * users must set min and max
  * scales list is hidden
* If unchecked : 
  * min and max readonly
  * scales list editable
  * min and max readonly because determined from scales list
  * no more warning like screenshot above
  * Only if the scale list is displayed, show the information text about print ?
  * ```json
        use_native_scales: true
        "mapScales": [
            100,
            500000
        ],
        "minScale": 100,
        "maxScale": 500000,
    ``` 
    Still mapscales with only max items ?

**Comment by Gustry** [comment]
I'm trying the PR. Looks good !

Side question, whatever the checkbox about native scales, if the map list has only two values, we have native, right ?

**Comment by Gustry** [comment]
> Side question, whatever the checkbox about native scales, if the map list has only two values, we have native, right ?

According to JS code, it seems not, but anyway, very rare to have only two values in this list.

https://github.com/3liz/lizmap-web-client/pull/4007/files#diff-0da40e308a26999f09137dd8e1062f96599436c1d67d4c1289054d4494539659R204

**Comment by rldhont** [comment]
@nboisteault @Gustry ready for reiews

**Comment by rldhont** [comment]
Linked to https://github.com/3liz/lizmap-plugin/pull/537

**Comment by Gustry** [comment]
> Side question, whatever the checkbox about native scales, if the map list has only two values, we have native, right ?

Indeed, it doesn't happen anymore.

LGTM for me

**Review by Gustry — APPROVED** [review]
From the test side

**Review by nboisteault — APPROVED** [review]
👍

**Pull request merged**
