### PR TITLE
Dataviz resizePlot on docks opened or closed

### PR DESCRIPTION
**Pull request by ygorigor**
Target version: LWC 3.4.4, LWC 3.5

If a dock with some plots is displayed, when another dock is opened the plots will be resized

### CODE REVIEW

**Comment by rldhont** [comment]
Hi @ygorigor thanks for your contribution.

Can you describe the targeted version of lizmap web client ?

**Comment by ygorigor** [comment]
> Hi @ygorigor thanks for your contribution.
> 
> Can you describe the targeted version of lizmap web client ?

I'm on master branch, LWC 3.5

**Review by mdouchin — CHANGES_REQUESTED** [review]
Thanks for your proposal. Could you also add this test for the bottom dock ?

**Comment by ygorigor** [comment]
> Thanks for your proposal. Could you also add this test for the bottom dock ?

Sorry, I don't know how to add test

**Comment by Gustry** [comment]
@ygorigor I guess @mdouchin didn't mean to add a "unit test", but the same kind of test you did for left and right dock but for the bottom one ?

I guess it resizes vertically ?

**Comment by ygorigor** [comment]
> @ygorigor I guess @mdouchin didn't mean to add a "unit test", but the same kind of test you did for left and right dock but for the bottom one ?
> 
> I guess it resizes vertically ?

@Gustry bottomdock has this check already.

**Review by mdouchin — APPROVED** [review]
Thanks !

**Pull request merged**
