### PR TITLE
Update OL to 9.0

### PR DESCRIPTION
**Pull request by nboisteault**
Funded by 3Liz

### CODE REVIEW

**Comment by Gustry** [comment]
With some nice new features :) 🚀

**Comment by mind84** [comment]
Hi @nboisteault,
any chance to backport this to 3.7?

Thanks

**Comment by Gustry** [comment]
>  any chance to backport this to 3.7?

I'm not able to comment on that. But you can just elaborate ? (features, bugfix interresting ?)

**Comment by mind84** [comment]
Hi @Gustry!

Yep, since 3.7 is the "current" version I think could be useful to backport also this PR (https://github.com/3liz/lizmap-web-client/pull/4357), in case it will be merged of course. In that case, Google Maps Tiles requires OL 9 to work. 

Also, I'm quite sure there is nothing to do on "Lizmap plugin side" for this potential backport since Google API Key is already supported.

Thanks!

**Comment by mind84** [comment]
@nboisteault 

Thanky you!

**Pull request merged**
