### PR TITLE
Fix visibility preset error

### LINKED ISSUE #3519: [Bug]: Theme/VisibilityPreset error (confusion between expanded and visible)
### What is the bug?

When selecting a theme in a project with layer groups, sometimes the visible layer are not correct.

### Steps to reproduce the issue

-

### Versions

3.5.8

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 20.4

### Browsers

Chrome

### Browsers version

Chrome 102

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by TeoGoddet**
Ticket : fix #3519 

Funded by Festival Balélec - Téo Goddet

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by Gustry** [comment]
The PHP Stan CI check must be fixed. Maybe it's the docstring about the return ?

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
Thanks @TeoGoddet

**Comment by nboisteault** [comment]
@rldhont @laurentj This PR changes `/lizmap/modules/lizmap/classes/qgisProject.class.php` but it should change `/lizmap/modules/lizmap/lib/Project/QgisProject.php` to work. Why are there those two similar files? Also it should not have been merged yet as unit tests can't pass.

**Comment by nboisteault** [comment]
@rldhont `/lizmap/modules/lizmap/classes/qgisProject.class.php` is deprecated since at least 3.5, it is written at top of the file. So a PR should be made with changes made in `/lizmap/modules/lizmap/lib/Project/QgisProject.php` and `testReadThemes()` in `tests/units/classes/Project/QgisProjectTest.php` as to be changed accordingly.

**Pull request merged**
