### PR TITLE
 tooltip - unwanted default layer

### PR DESCRIPTION
**Pull request by josemvm**
to prevent an unwanted default layer to be load when initializing the tool
https://github.com/3liz/lizmap-web-client/issues/706

### CODE REVIEW

**Comment by rldhont** [comment]
Thanks to trying to fixed #706, but your code is not enough to completely fixed it.
We firstly needs an option to disable or not: loading a layer at the tooltip dock displayed.
We have to enhance the JavaScript to well ended if the GeoJSON is not complete or if the request not well finished.

**Comment by josemvm** [comment]
ok, for now it's just a workaround

**Comment by rldhont** [comment]
Why did you close your PR ? I was thinking to reuse it and enhance. I'd like the idea to add a string in the select. Can you restore your branche and reopen it ? Thanks

**Comment by josemvm** [comment]
sorry, you can reuse the code in a timely manner

**Comment by rldhont** [comment]
I have opened an issue #1123 to save your solution to fix #706

**Pull request closed without merging**
