### PR TITLE
[Backport release_3_4][BUGIX] Selection & Export - Use the selectiontoken & POST to QGIS Server

### PR DESCRIPTION
**Pull request by rldhont**
Mannually backport #2608

### CODE REVIEW

**Review by mdouchin — APPROVED** [review]

**Review by nboisteault — COMMENTED** [review]
Please run Cypress in CI and give me the link.

**Comment by rldhont** [comment]
> Please run Cypress in CI and give me the link.

@nboisteault: Startup failure https://github.com/rldhont/lizmap-web-client/actions/runs/1607576449

**Comment by rldhont** [comment]
> > Please run Cypress in CI and give me the link.
> 
> @nboisteault: Startup failure https://github.com/rldhont/lizmap-web-client/actions/runs/1607576449

@nboisteault new action https://github.com/rldhont/lizmap-web-client/actions/runs/1607581669

**Review by nboisteault — APPROVED** [review]

**Comment by rldhont** [comment]
> > > Please run Cypress in CI and give me the link.
> > 
> > 
> > @nboisteault: Startup failure https://github.com/rldhont/lizmap-web-client/actions/runs/1607576449
> 
> @nboisteault new action https://github.com/rldhont/lizmap-web-client/actions/runs/1607581669

2 tests failed

```
  1) External WMS layers
       should get correct mime type in response:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#layer-bakeries button`, but never found it.
      at Context.eval (http://localhost:8130/__cypress/tests?p=cypress/integration/external_wms_layer-ghaction.js:129:8)
```

```
  1) Form edition all field type
       boolean, dropdown menu:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#jforms_view_edition_boolean_nullable`, but never found it.
      at Context.eval (http://localhost:8130/__cypress/tests?p=cypress/integration/form_edition_all_field_type-ghaction.js:184:8)
```

**Pull request merged**
