### PR TITLE
Fix support of boolean values in qgis form properties with Qgis 3

### PR DESCRIPTION
**Pull request by laurentj**
Depending of the version of Qgis, we have 0/1 or 'true'/'false' as values, for boolean properties. We didn't support fully 'true'/'false' values.

### CODE REVIEW

**Comment by rldhont** [comment]
@laurentj you can merge

**Comment by josemvm** [comment]
hi @laurentj 
there is a problem with this fix, the combo boxes does not appear in the form...

**Comment by josemvm** [comment]
on qgis server 2

**Comment by nboisteault** [comment]
@josemvm this fix is for [LWC 3.3 which is not compatible with QGIS Server 2.18](https://github.com/3liz/lizmap-web-client#versions).

**Comment by josemvm** [comment]
yes, i' m using qgis server 2.18 with lizmap 3.3 and until now everything works fine :-)

**Comment by rldhont** [comment]
@laurentj regression with QGIS 2.18 project file.

**Comment by rldhont** [comment]
@josemvm bug opened https://github.com/3liz/lizmap-web-client/issues/1589, can you provide screenshots ?

**Pull request merged**
