### PR TITLE
Lint with PHP-CS-Fixer 2.17.1

### PR DESCRIPTION
**Pull request by rldhont**
After updated php-cs-fixer to version 2.17.1, more files has to be updated.

This fix the github action.

### CODE REVIEW

**Comment by rldhont** [comment]
Lint fixed

**Review by alagroy-42 — APPROVED** [review]

**Comment by nboisteault** [comment]
@rldhont PR for master not release_3_4?

**Comment by Gustry** [comment]
Thanks for fixing it !

Shouldn't you target the release 3.4 branch ?

**Comment by rldhont** [comment]
@nboisteault @Gustry thanks for pointing it. I target 3.4. You can merge ;-)

**Review by nboisteault — APPROVED** [review]

**Pull request merged**
