### PR TITLE
Release 3.5.2

### PR DESCRIPTION
**Pull request by opbernardo**
Hi,

I just installed Lizmap Webclient 3.5.2, and I found the edition tool It does not work properly...

With the tool, I can draw, lines, points and polygons, but I can not edit them!!

This is a bug?

With the Lizmap Webclient 3.5.1 version, is all ok!

Thank you.

Orlando

01_LWC_351
02_LWC_351
03_LWC_351
04_LWC_352
05_LWC_352
06_LWC_352

### CODE REVIEW

**Comment by Gustry** [comment]
You have opened a pull request (for code changes). Please open a ticket instead.

**Comment by opbernardo** [comment]
Where can I open the ticket please?

**Comment by josemvm** [comment]
here https://github.com/3liz/lizmap-web-client/issues

**Comment by opbernardo** [comment]
Thanks josemvm

**Pull request closed without merging**
