### PR TITLE
[Bugfix] Support openTopoMap

### LINKED ISSUE #3671: [Bug]:
### What is the bug?

With the new version of Lizmap you can use opentopomap as base layer, but it doesn't appear in the base layer list when you open the map on the web

### Steps to reproduce the issue

image

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap plugin : 3.13.0
* QGIS Desktop : 3.28.5
* QGIS Server : 3.30.2
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

_No response_

### Operating system

Ubuuntu 22

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

chrome 112

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rldhont**
Fixes #3671 [Bug]: OpenTopoMap base map layer don't work in Lizmap

### CODE REVIEW

**Review by Gustry — COMMENTED** [review]
Is printing covered ?
I don't see any occurence of `open-topo-map` CF https://docs.lizmap.com/current/fr/publish/configuration/print.html#allow-printing-of-external-baselayers

**Comment by rldhont** [comment]
@Gustry good check

**Comment by rldhont** [comment]
@nboisteault not before we merge my work and your work.

**Comment by Gustry** [comment]
Related to #3073 and #3656, when we will release 3.7.0, it's very easy to forward port by cherry-picking this unique commit if needed. (if it has not been merged in master, but 3.6 only)

**Comment by Gustry** [comment]
This PR is not working, because the plugin is generating a true boolean value, not a string.

**Pull request merged**
