### PR TITLE
Allow multiple atlas definition

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by Gustry** [comment]
Not even merged in lizmap-plugin, already available in LWC ! ;-) Well done !

Does it fit with https://github.com/3liz/lizmap-plugin/pull/170#issuecomment-557154927 ?

**Comment by rldhont** [comment]
@nboisteault confilct to resolved before merging thanks

**Comment by rldhont** [comment]
@nboisteault new conflict ;-)

I'll merge after

**Comment by nboisteault** [comment]
> @nboisteault new conflict ;-)
> 
> I'll merge after

Where ?

**Comment by rldhont** [comment]
> > @nboisteault new conflict ;-)
> > I'll merge after
> 
> Where ?

Sorry, it is for rebase, I merge.

**Comment by Gustry** [comment]
@nboisteault 

Sorry to ask this after merge, is-it possible to switch from (the current implementation) : 

```
{
    "options": {
        ..........
        "atlasAutoPlay":"True",
        "atlasShowAtStartup": "True",
        ..........
     }
    "atlas": [
        {
            "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
            "primaryKey": "_code_chantier",
            "displayLayerDescription": true,
            "featureLabel": "id",
            "sortField": "id",
            "highlightGeometry": true,
            "zoom": "",
            "duration": 5,
            "displayPopup": true,
            "triggerFilter": true
        },
        {
            "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
            "primaryKey": "_code_chantier",
            "displayLayerDescription": true,
            "featureLabel": "id",
            "sortField": "id",
            "highlightGeometry": true,
            "zoom": "",
            "duration": 10,
            "displayPopup": true,
            "triggerFilter": true
        }
    ]
}
```

to 

```
{
    "options": {
        ..........
        "atlasAutoPlay":"True",
        "atlasShowAtStartup": "True",
        ..........
     }
    "atlas": {
        'layers': [
            {
                "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
                "primaryKey": "_code_chantier",
                "displayLayerDescription": true,
                "featureLabel": "id",
                "sortField": "id",
                "highlightGeometry": true,
                "zoom": "",
                "duration": 5,
                "displayPopup": true,
                "triggerFilter": true
            },
            {
                "layer": "output_4505f94b_6df2_478b_924c_5ecfeb6b4165",
                "primaryKey": "_code_chantier",
                "displayLayerDescription": true,
                "featureLabel": "id",
                "sortField": "id",
                "highlightGeometry": true,
                "zoom": "",
                "duration": 10,
                "displayPopup": true,
                "triggerFilter": true
            }
        ]
    }
}
```

So later, in Lizmap 4, it will allow us to have cleaner configuration like:
```
    "options": {
        ..........
        ..........
     },
    "atlas": {
        'layers': [
        ],
        config:{
             `autoPlay`: foo
             `showAtStartup`: bar
        }
    }
```

**Pull request merged**
