### PR TITLE
[Bugfix] Load relations from embedded layers

### PR DESCRIPTION
**Pull request by mind84**
Ticket : #3776

Funded by Faunalia

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by nboisteault** [comment]
@mind84 thanks for this PR. Please tell us what bug does it fix? Also could you add a Lizmap project in `\tests\qgis-projects\tests`, a unit test in `\tests\units` and/or a end2end test in `\tests\end2end\playwright`?

**Comment by mind84** [comment]
> could you add a Lizmap project in `\tests\qgis-projects\tests`, a unit test in `\tests\units` and/or a end2end test in `\tests\end2end\playwright`?

Hi @nboisteault, 
of course, I'll try to implement some test

Thank you!

**Comment by mind84** [comment]
Hi @nboisteault, @Gustry ,
I've added a couple of test projects, unit test and a playwright file for e2e. I think this is a good start, but please let me know if you any suggestion to implement these test files, I'm glad to update them.

Thank you!

**Comment by Gustry** [comment]
Unrelated test failure about metadata. Fixed in master, you can rebase if you want or skip this failing test

**Comment by Gustry** [comment]
I meant a rebase/merge if your local master branch was up to date (by fetching and applying) ;-)
You should clean the PR with clean set of commits.

**Comment by mind84** [comment]
> I meant a rebase/merge if your local master branch was up to date (by fetching and applying) ;-) You should clean the PR with clean set of commits.
@Gustry,
I think it's better to close this pull request. I'll make a new one, I think it's more clean.
Sorry

**Comment by Gustry** [comment]
>  I think it's better to close this pull request. I'll make a new one, I think it's more clean.

Up to you, it's still possible to clean and make a totallly clean PR here, it depends on you how you are confident with the git gymnastic ;-) Feel free to make a new one, it might easier ;-)

**Comment by Gustry** [comment]
I just realized that : 

image

It's better to make your own branch, I think. Committing straight on master to make a PR might is easier but maybe that's why you got issues when you tried to upgrade your branch.

**Comment by mind84** [comment]
> I just realized that :
> 
> image
> 
> It's better to make your own branch, I think. Committing straight on master to make a PR might is easier but maybe that's why you got issues when you tried to upgrade your branch.

Yep, that exactly the issue. And of course the branch is the right way, I don't pay attention on that. 
I'll make a new one 
Thanks

**Pull request closed without merging**
