### PR TITLE
Remove app context from OGCRequest constructor

### PR DESCRIPTION
**Pull request by laurentj**
Requests objects should rely on the same app context of the project object.
It is not consistent to have different appContext objects (and it could
brake some unit tests).

* Funded by 3Liz

### CODE REVIEW

**Comment by laurentj** [comment]
This is a draft, i will update the patch after the landing of #2348

**Review by mdouchin — APPROVED** [review]
Thanks ! @rldhont we need to check the modules for the use of the OGCRequest class

**Comment by laurentj** [comment]
@mdouchin  I already check: they are using deprecated classes of requests so no impact. However, they should use the new classes AND old classes at the same time to be compatible with lizmap 3.4 and lower.

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
LGTM thanks @laurentj

**Pull request merged**
