### PR TITLE
Update attributeTable.js

### PR DESCRIPTION
**Pull request by RobiFag**
## Description
This pull request is related to the issue #747 . As explained in the issue we have made some changes to a js file suggested by @mdouchin in order to display description labels instead of values in the attribute table for columns with ValueMap widget (see https://github.com/3liz/lizmap-javascript-scripts/pull/25). The script works perfectly with text columns but the attributeTable.js file requires some changes in order to make it work also with numeric columns.
The js script, in fact, is based on the translateWfsFieldValues() function which is triggered only for text columns in the attributeTable.js file. Hence I added the same function used for cType default to the numeric cType condition. With these changes to the attributeTable.js file, the js script seems to work perfectly both with text and numeric columns.

### CODE REVIEW

**Comment by RobiFag** [comment]
> Thanks for the PR !
> Could you please refactor the code by creating a dedicated function used in both "integer" and "default" cases ?

Hi @mdouchin thank you for the suggestion...I will think about refactoring the code as you suggested and changing the code in the proper way in the next days.

**Comment by RobiFag** [comment]
Hi @mdouchin sorry for the delay! I tried to make the changes you requested, I hope it is fine!
This PR is strictly connected to this one https://github.com/3liz/lizmap-javascript-scripts/pull/25 which is still open. If you have any suggestion or comments about both, please let me know.

**Comment by laurentj** [comment]
Please update the new CHANGELOG-3.4.md with description of what it changes for the user (if it is relevant)

**Comment by RobiFag** [comment]
Hi @laurentj maybe it's not necessary to add a description to the changelog since this PR regards minor changes strictly related to the use of an additional js file that I added to the lizmap-javascript-scripts (3liz/lizmap-javascript-scripts#25). But if you prefer I can modify the changelog, please let me know.

**Comment by rldhont** [comment]
@RobiFag even if a jascript exists, it is better to change the changelog

**Comment by rldhont** [comment]
Hi @RobiFag we would like to merge your work in master to be part of lizmap-web-client 3.4.

Can you please update the CHANGELOG-3.4.md file ?

**Comment by RobiFag** [comment]
> Hi @RobiFag we would like to merge your work in master to be part of lizmap-web-client 3.4.
> 
> Can you please update the CHANGELOG-3.4.md file ?

Hi @rldhont sorry for the delay! I have just created a new PR in order to update the changelog

**Comment by RobiFag** [comment]
Hi! I found a bug in the code developed for this PR. How can I fix it? do I have to open a new PR or is it better to add the code to this one? @rldhont

**Comment by nboisteault** [comment]
@RobiFag please open a new PR.

**Comment by Gustry** [comment]
@RobiFag This PR has been merged, so you need a new one.

**Comment by RobiFag** [comment]
I have just checked the attributeTable.js and I noticed you have already fixed the bug (column with media path) I was talking about.
Thanks!

**Pull request merged**
