### PR TITLE
adding ISO Date Format handling + seconds in datetimepicker

### LINKED ISSUE #1888: Date/Time with timezone
### What is the bug?
With the support of QGIS Date/Time format, lizmap loose the timezone support

### Steps to reproduce the issue

1. Go to Postgres and create a layer with a field `timestamp with time zone`
2. Go to QGIS 
    1. Add the layer
    2. Open layer properties
    3. Go to Attributes Form
    4. Click on the field `timestamp with time zone`
    5. Choose Date/Time Widget Type
    6. Choose ISO date time
    7. Choose Custom Widget Display with `yyyy-MM-dd HH:mm:ss +t`
3. Configure the project with Lizmap plugin, set the layer in edition capabilitie
4. Try to edit the layer and set the field `timestamp with time zone`
5. See that the form is locked

### Expected behavior
The field has to be saved

### Screenshots and logs

image001

### Environment

 - Lizmap version: 3.3.12-pre
 - QGIS Server FULL version: 3.4
 - QGIS Desktop FULL version: 3.4
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Firefox

### PR DESCRIPTION
**Pull request by alagroy-42**
* Ticket : fix #1888

### CODE REVIEW

**Review by laurentj — COMMENTED** [review]
how these patch enable the support of timezone?

Should the timezone have to be editable?

**Comment by rldhont** [comment]
@alagroy-42 has you tested with https://github.com/3liz/lizmap-web-client-demo/tree/master/tests_edition

**Review by nboisteault — APPROVED** [review]
I've tested. It is OK.

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
thanks @nboisteault @alagroy-42

**Pull request merged**
