### PR TITLE
[Feature] Draw geometry directly with geolocation dock

### PR DESCRIPTION
**Pull request by rldhont**
Add some tools in the geolocation dock to add point to geometry

### CODE REVIEW

**Comment by rldhont** [comment]
@jancelin and @josemvm can you test this PR ?

**Comment by josemvm** [comment]
hi @rldhont 

it works!

- there is a significant delay between Edition/**Add** and Geolocation/**Edition** (appear)

- there is a more significant delay between Edition/**Cancel** and Geolocation/**Edition** (disappear)

- Geolocation/Edition/**linked to geolocation** - check/uncheck is synchronized with Manage point/vertex coordinates/**linked to geolocation** but the reverse doesn't

- a space between check box and string imagem


> mobile mode:
when the user try to Addfeature from Editiontool the form doesn't appear, it's necessary to click again on the Editiontool and the same behavior for all options After saved (the form doesn't appear)
 

imagem

**Comment by jancelin** [comment]
hi @rldhont 
non-blocking: I'm making the same comments as @josemvm.
Otherwise it works fine. :)

**Comment by rldhont** [comment]
@josemvm and @jancelin, I have updated the code to take into account:
* fix delay between Edition/Add and Geolocation/Edition
* fix delay between Edition/Cancel and Geolocation/Edition
* fix check/uncheck is synchronized with Manage point/vertex coordinates/linked to geolocation but the reverse doesn't
* fix space between check box and string
* fix space beetwen geolocation button bar and edition

@josemvm about edition in mobile ode, we have to review the way form is displayed.

**Pull request merged**
