### PR TITLE
UI - Update to Lizmap server plugin and its version

### PR DESCRIPTION
**Pull request by Gustry**
Linked to #2972 @mdouchin

It would be nice to hardcode as well the QGIS version, so we don't need to translate in Transifex everytime we change the QGIS version (and Lizmap server plugin version as well)

### CODE REVIEW

**Comment by Gustry** [comment]
I didn't find in a XML jform file how to dynamically format a string.

My PHP are quite rusty, trying to manage how to format strings in a template.

**Review by mdouchin — APPROVED** [review]
Thanks !

**Comment by Gustry** [comment]
I finally found how to make jform with a dynamic help string.

@laurentj and @mdouchin Where would be the best place to make `$qgisMinimumVersionRequired` and `$lizmapPluginMinimumVersionRequired` global ? (for these two files and later for #2972)

**Comment by mdouchin** [comment]
> I finally found how to make jform with a dynamic help string.
> 
> @laurentj and @mdouchin Where would be the best place to make `$qgisMinimumVersionRequired` and `$lizmapPluginMinimumVersionRequired` global ? (for these two files and later for #2972)

I would say we could add them in the `mainconfig.ini.php`, or better in `lizmapConfig.ini.php` ? Or we could create a new file `lizmapQgisServerVersionTable.ini.php` with these variables to facilitate it update when releasing a new version (I prefer this dedicated file)

**Comment by Gustry** [comment]
Ok, let's try in a next PR, related to #2972 . Merging in the meantime.

**Pull request merged**
