### PR TITLE
Improve mobile ui

### PR DESCRIPTION
**Pull request by nboisteault**
## Description
Improve user interface for smartphones, touchscreens.

### CODE REVIEW

**Comment by nboisteault** [comment]
@mdouchin WIP

**Comment by nboisteault** [comment]
@mdouchin Did you try to turn the left bar to responsive? Doc part "Responsive navbar" in https://getbootstrap.com/2.3.2/components.html#navbar

**Comment by nboisteault** [comment]
A first try based on https://codepen.io/erikterwan/pen/EVzeRP : 
hamburger

**Comment by laurentj** [comment]
Please update the new CHANGELOG-3.4.md with description of what it changes for the user.

**Comment by rldhont** [comment]
@nboisteault update the changelog then we can merge.

**Comment by nboisteault** [comment]
@rldhont it is a draft. I have some changes to make.

**Comment by nboisteault** [comment]
@mdouchin do you validate what can be saw in gif ?

**Comment by nboisteault** [comment]
I'm merging this PR and opening a new PR for hamburger menu.

**Pull request merged**
