### PR TITLE
Adding new test to the feature of filtering by tags

### PR DESCRIPTION
**Pull request by drillinP**
New PR to add test to the feature of filter by tags.

### CODE REVIEW

**Comment by nboisteault** [comment]
@drillinP Please rebase this PR with `master` and target `master` not `release_3_4`.

**Comment by drillinP** [comment]
@nboisteault I have a problem with some file when i want rebase with `master` in local. some files change on their own like: `lizmap/var/config/admin/config.ini.php`

**Comment by nboisteault** [comment]
@drillinP Do `git status`. If those files have just spaces that differ, you can `git restore` them.

**Comment by drillinP** [comment]
@nboisteault I use git restore but this problem appear when I use git merge

**Comment by Gustry** [comment]
@drillinP When writing an error, you should include the result of `git status` for instance, add the full error message and also your workflow of git commands. There are so many ways and commands to work with git ;-)
And I don't think `git merge` is the good one :)

**Pull request closed without merging**
