### PR TITLE
Always display form in edition mode

### PR DESCRIPTION
**Pull request by nboisteault**
* Funded by 3Liz

### CODE REVIEW

**Comment by nboisteault** [comment]
Note to me. I have to add a test with a spatial layer.

**Comment by nboisteault** [comment]
@mdouchin @rldhont I finally changed this PR to only fix the bug and not change the form behavior as 3.4.1 is a bugfix release.
Please test (dnd_form in /tests) and merge as I'll be busy this morning. Thanks.

**Comment by mdouchin** [comment]
@nboisteault @rldhont 

* in desktop mode, with the last changes, the form does not display the input fields.

Screenshot_2021-01-13 dnd_form - tests - Lizmap

* in mobile it is the same, but there is another issue: the attribute table does not hide automatically nor the form shows up automatically 

https://user-images.githubusercontent.com/3492210/104457903-ec2b6400-55aa-11eb-8ef2-1432a84213e2.mp4

**Comment by mdouchin** [comment]
I would prefer to change the behaviour, even if 3.4.1 is a bugfix release. 3.4.0 is young, and better do this change now than never

**Comment by nboisteault** [comment]
@mdouchin did you refresh js cache?

**Comment by nboisteault** [comment]
@rldhont @mdouchin ready for review.

**Comment by nboisteault** [comment]
@mdouchin thumb up means you've made the review? :)

**Comment by mdouchin** [comment]
It means I read it carefully but have not tested it yet. Do you need a "human" review or do you trust the new Cypress automatic tests (great to see them land in Lizmap Web Client !!!) ?

**Comment by nboisteault** [comment]
@mdouchin @rldhont  I have added tests concerning digitizing tab visibility but I'd like at least one reviewer to manually test as this PR is about edition.

**Comment by nboisteault** [comment]
@mdouchin gentle ping :)

**Review by drillinP — APPROVED** [review]
tested and it's ok

**Pull request merged**
