### PR TITLE
[Backport release_3_5] [PHP] Get cached Polygon filter for project, layer, login and editing context

### PR DESCRIPTION
**Pull request by rldhont**
Manually Backport https://github.com/3liz/lizmap-web-client/pull/3895
Authored by: @rldhont

### CODE REVIEW

**Comment by rldhont** [comment]
@Gustry the `requests-metadata-ghaction.js` cypress test failed. It is not related.

**Comment by Gustry** [comment]
It was already fixed in the branch, I just pressed the rebased button ;-)

**Comment by rldhont** [comment]
@nworr the playwright Input type number test failed.

**Comment by nworr** [comment]
the feature wasn't backported to 3.5, but unfortunately the test was backported, you can ignore

**Comment by rldhont** [comment]
@nworr have I to remove `tests/end2end/playwright/edition-form.spec.ts` ?

**Comment by nworr** [comment]
Yes, it seems the whole file contain tests unrelated to 3.5 (wrong backport from @nboisteault  ?)

**Pull request merged**
