### PR TITLE
move close button in right dock

### PR DESCRIPTION
**Pull request by josemvm**
move button position in right dock - like left dock
imagem

### CODE REVIEW

**Comment by rldhont** [comment]
Does it work on mobile screen ?

**Comment by nboisteault** [comment]
@rldhont I've tested it is ok.

**Comment by nboisteault** [comment]
@josemvm could you change target branch to release_3_2 ?

**Comment by josemvm** [comment]
imagem

that's all

**Comment by rldhont** [comment]
Thanks @josemvm can you do it on release_3_2 and open a new PR ?

**Pull request closed without merging**
