### PR TITLE
[Bugfix] Download export with the filename

### PR DESCRIPTION
**Pull request by rldhont**
The changes done with #2892 [Bugfix] Force to open GetPrint in blank window do not provide the filename and extension

* Funded by TACTIS

### CODE REVIEW

**Comment by rldhont** [comment]
The failed test is not linked to my changes. Something wrong with QGIS Server 3.22 and FeatureCount in legend image.

**Review by mdouchin — APPROVED** [review]

**Comment by rldhont** [comment]
Thanks @nboisteault I have updated the end2end print test.

**Comment by nboisteault** [comment]
Thanks @rldhont I'm looking why Cypress fails.

**Review by nboisteault — APPROVED** [review]

**Comment by rldhont** [comment]
@nboisteault no more issue in Chrome ?

**Pull request merged**
