### PR TITLE
Fix regrssion : keep atlasprint plugin

### PR DESCRIPTION
**Pull request by rldhont**
QGIS Server does not work atlas print does.

### CODE REVIEW

**Review by nboisteault — APPROVED** [review]

**Review by Gustry — CHANGES_REQUESTED** [review]
* The file given to the user is a random string `ts_gkX7a` and the output format extension is missing. Extension is required, using a proper name
* The print on the "Montpellier" project http://localhost:8130/index.php/view/map?repository=montpellier&project=montpellier is not printing base layer, is-that correct ?

**Comment by rldhont** [comment]
Changes done

**Comment by Gustry** [comment]
The AtlasPrint is not required to run LWC. Pressing the button will lead to a 404 from QGIS server and the button will not work. Possible to use the PHP class `lizmap/modules/lizmap/lib/Server/Server.php` ?

**Comment by Gustry** [comment]
Changes in the documentation : https://github.com/3liz/lizmap-documentation/pull/246

Your PR is partially reverting 25ee656a54609fa3c7fe921f52fb98c43a798196, just to keep track for later

**Review by Gustry — APPROVED** [review]
Looks better to me

**Comment by Gustry** [comment]
Another related commit in the plugin [2c504c0faa86972d1136da16f4dc4a78f6c4a7ee](https://github.com/3liz/lizmap-plugin/commit/2c504c0faa86972d1136da16f4dc4a78f6c4a7ee)

**Pull request merged**
