### PR TITLE
adding documentation generation environment

### PR DESCRIPTION
**Pull request by alagroy-42**
Adding a documentation generation environment working with phpDocumentor.
It should automatically generate web pages with the documentation and host it on GitlabPages

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by Gustry** [comment]
Side question, why is-it closed?

**Comment by Gustry** [comment]
Thanks for reopening.
Your stage is missing a `tags` statement, it won't be executed by gitlab AFAIK.
What do you do with generated files in `docs/` ? Will it be published automatically in Gitlab pages?
Maybe you should do this PR in Gitlab to make it run by the CI?

Let's wait for @laurentj

**Comment by rldhont** [comment]
Makefile en conflit

**Comment by rldhont** [comment]
@alagroy-42 conflict to resolve

**Review by mdouchin — APPROVED** [review]
LGTM thanks

**Comment by nboisteault** [comment]
@rldhont @mdouchin what do we do with this PR?

**Comment by Gustry** [comment]
IMHO, we should have the HTML generation.
So we should : 
* rebase, fix conflict
* check that the given `make doc` works and generate some HTML files

The gitlab-ci file will fail for now because there isn't any `tag` statement. Then later, we can decide where to publish the HTML, on docs.3liz.org temporarily ?, docs.lizmap.com ?

**Comment by Gustry** [comment]
I think it would be nice to have, but I'm not a PHP dev so I won't be able to do something here.

**Pull request closed without merging**
