### PR TITLE
[FEATURE] New Atlas tool - Navigate through the features of a layer

### PR DESCRIPTION
**Pull request by mdouchin**
Navigate through features and for each feature, optionally:
* highlight the feature
* zoom or center to the feature
* display the feature popup
* filter the layer for the feature (and its children)

To navigate you can:
* use the combobox listing of feature.
* use the previous or next button
* use the play button to automatically move to the next feature after some time

The map editor can modify these options with Lizmap plugin

### CODE REVIEW

**Comment by mdouchin** [comment]
@josemvm @rldhont you need to use version master of Lizmap plugin to configure the Atlas tool for your map ;)
Enjoy !

**Comment by josemvm** [comment]
hi @mdouchin 

awesome!!! 👍 

thanks

**Comment by josemvm** [comment]
i think when the user closes/stops the tool it could destroy the filter and the highlighted feature...
e.g. to remove the highlighted feature the user needs to use the locating tool...

thanks again!

**Comment by mdouchin** [comment]
@josemvm done (rebased this branch). I will merge if ok

**Pull request merged**
