### PR TITLE
proxy external WMS

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
Is this commit ok now? Will it be merged in a future release?

**Comment by rldhont** [comment]
I'll merge it today. We are also fixes last issues.

**Comment by nboisteault** [comment]
Great! Thank you.

**Comment by rldhont** [comment]
Thanks for your contribution! If you wanna fix other issue, your help is welcome

**Comment by nboisteault** [comment]
You're welcome. I'll try to find some time to help.

**Comment by nboisteault** [comment]
Hi @mdouchin, I'll take a look today.

**Pull request merged**
