### PR TITLE
coding style

### PR DESCRIPTION
**Pull request by alagroy-42**
Coding style modification on all lizmap Classes

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
Can we have a test to check php coding style ?

**Comment by Gustry** [comment]
Something like https://github.com/github/super-linter ?
CC @nboisteault

**Comment by laurentj** [comment]
@rldhont you must use php-cs-fixer, see our doc : https://github.com/3liz/lizmap-web-client/blob/master/CONTRIBUTING.md#coding-style

**Comment by rldhont** [comment]
@laurentj do we approve this PR ?

**Pull request merged**
