### PR TITLE
[Tests] e2e: check config.options.hideProject: "True"

### PR DESCRIPTION
**Pull request by rldhont**
New tests to check the lizmap config options hide project.
The project is empty: no layers, no other config.

Funded by 3Liz

### CODE REVIEW

**Review by Gustry — APPROVED** [review]
LGTM,

Side question, when is this option useful because the project is not visible for anyone ?
I thought it was only to make it hidden in the landing page but the project would still be accessible with a direct URL... but it seems it's not the case.

**Comment by rldhont** [comment]
This option is made to hide project in the landing page and provide only OGC services.

**Review by nboisteault — APPROVED** [review]

**Comment by nboisteault** [comment]
@rldhont PHPStan has been updated to https://github.com/phpstan/phpstan/releases/tag/1.7.12 . That's why it has failed.

**Comment by rldhont** [comment]
> This option is made to hide project in the landing page and provide only OGC services.

It also avoid map view, only services.

**Pull request merged**
