### PR TITLE
[FEATURE] Attribute table - Fix header at the top of the tables

### PR DESCRIPTION
**Pull request by mdouchin**
This feature helps the user to scroll through the features by keeping the header columns always on top.

### CODE REVIEW

**Comment by josemvm** [comment]
very nice @mdouchin!

and for the subpanels?...

https://github.com/3liz/lizmap-web-client/issues/590

**Comment by mdouchin** [comment]
@josemvm Should be ok for the subpanels too. Please check ;)

**Comment by josemvm** [comment]
sorry, it's OK and very very nice :-)

thanks @mdouchin

**Comment by mdouchin** [comment]
@jancelin could you please try this branch before I merge it into master ?

**Comment by jancelin** [comment]
OK, thanks @mdouchin

**Comment by mdouchin** [comment]
Merged manually  2d88a86ec62255f3f7ca2fbe478cd2ae671b534d

**Pull request closed without merging**
