### PR TITLE
Merge release 3.2 in 3.3 with Wrong UPDATE query sent to PostgreSQL, data loss

### PR DESCRIPTION
**Pull request by rldhont**
https://github.com/3liz/lizmap-web-client/pull/1664

https://github.com/3liz/lizmap-web-client/pull/1667

https://github.com/3liz/lizmap-web-client/pull/1669

### CODE REVIEW

**Comment by nboisteault** [comment]
@rldhont #1629 has been merged by @laurentj yet. Do you want some tests on your branch ?

**Comment by rldhont** [comment]
@nboisteault I have tested with montpellier project. I would like you also test it.

**Comment by laurentj** [comment]
I merged release_3_2 into release_3_3 (before your commit of this bug fix), and then I merged  release_3_3 into your branch, so we can see only changes you made for the bug. So it is more easy to review. I'm going to review it.

**Comment by rldhont** [comment]
Thanks @laurentj waiting for @nboisteault review

**Comment by rldhont** [comment]
Manually merge with 47a28fe15523f25f75b74170d7d52dd7c81b5f78

**Pull request closed without merging**
