### PR TITLE
Add an hidden table to popup with children

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by nboisteault** [comment]
@mdouchin finally I've added a table in backend. I'm going to add an HTML button to toggle visibility now.

**Comment by nboisteault** [comment]
compact_explode_table

**Comment by josemvm** [comment]
@nboisteault thanks for this new feature!

did you define some criteria for children ordering in popup?

i think it would be a good idea to have a sorting criterion, for example the primary key or another field to be defined in the plugin... and not a random order

**Comment by mdouchin** [comment]
thanks @nboisteault Ordering could be achieved perhaps with no pain by "datatabling" the table, so that people can order by any columns

```javascript
$('#myTable').DataTable();
```
See: https://datatables.net/examples/basic_init/zero_configuration.html

**Comment by rldhont** [comment]
You can merge

**Pull request merged**
