### PR TITLE
Install external modules with Composer

### PR DESCRIPTION
**Pull request by laurentj**
Install source code of jCommunity and ldapdao with Composer, instead of copying their source code into our repository.

### CODE REVIEW

**Comment by mdouchin** [comment]
Ok for me. Would the `make build` command do the magic for us ?

**Comment by nboisteault** [comment]
@laurentj I followed instructions [here](https://github.com/3liz/lizmap-web-client/tree/master/lizmap/my-packages) till `composer install` but LWC did not start. Did I misunderstood ?

**Comment by laurentj** [comment]
@mdouchin yes of course, this is already the case since weeks ;-)

@nboisteault sorry, but telling "LWC did not start" don't help me. And this is not related to this PR. What is the problem exactly?

**Comment by nboisteault** [comment]
@laurentj I'd like to try in docker. Can you tell me how I can launch composer in docker machine ?

**Pull request merged**
