### PR TITLE
[Feature] Embed controller

### PR DESCRIPTION
**Pull request by rldhont**
Defined a controller to provide a map to embed it with an adapted style.

### CODE REVIEW

**Comment by rldhont** [comment]
@josemvm and @mdouchin can you test the UI ? thanks

**Comment by josemvm** [comment]
hi @rldhont 

when i try to load a map project, i get these error messages:

> Error 500. A technical error has occured. Sorry for this trouble.

and

> 2017-11-09 15:50:25     10.27.10.180    error   2017-11-09 15:50:25     [0]     (210)The given locale key "view~map.bottomdock.toolbar.btn.clean.title" does not exists in the default lang and in the fallback lang for the UTF-8 charset   /var/www/html/lizmap-web-client-master/lib/jelix/core/jLocale.class.php 97

**Comment by rldhont** [comment]
@josemvm it seems you have locally an updated file. Because the locale `bottomdock.toolbar.btn.clean.title` is not used but `bottomdock.toolbar.btn.clear.title` is used and defined.
Can you verified your files:
```
lizmap/modules/view/templates/map_dock.tpl
lizmap/modules/view/templates/map_rightdock.tpl
lizmap/modules/view/templates/map_bottomdock.tpl
lizmap/modules/view/templates/map.tpl
```

**Comment by josemvm** [comment]
sorry, you're right

`<iframe width="400" height="300" frameborder="0" style="border:0" src="http://gasur.cmarl.pt/index.php/view/embed/?repository=montpellier&project=montpellier&layers=B00TFTTTTFFFTTFTT&bbox=402080.797727%2C5385290.67936%2C462083.864922%2C5424464.65635&crs=EPSG%3A3857&layerStyles=tramway%3Ablack" allowfullscreen></iframe>`

now it works!, but the code generated for embed doesn't work on my html test page...

**Comment by rldhont** [comment]
@josemvm does the domain name, `gasur.cmarl.pt` is the issue ?

**Comment by josemvm** [comment]
no, it doesn't. gasur.cmarl.pt it's just a local domain. the generated code only creates a blank page, without errors...

**Comment by rldhont** [comment]
@josemvm here is my HTML test page:
```html
<!DOCTYPE HTML>
<html lang="fr-FR"><head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
<title>Lizmap - embed</title>
</head>
<body>
<iframe width="600" height="450" frameborder="0" style="border:0" src="http://lizmap.localhost/index.php/view/embed/?repository=montpellier&project=montpellier&layers=B00TFTTTFFFTTTFTT&bbox=407679.810048%2C5393488.550642%2C456484.852601%2C5416266.785068&crs=EPSG%3A3857&layerStyles=tramway%3Ablack" allowfullscreen></iframe>
</body>
```
And it works

**Comment by josemvm** [comment]
i will try asap and give you feedback

**Comment by rldhont** [comment]
The issue comes from your server configuration that prevent using your website in iframes: https://stackoverflow.com/questions/38699221/load-denied-by-x-frame-options-does-not-permit-framing

**Comment by josemvm** [comment]
ok i'll checkout the problem, but i didn't do anything to prevent it...
thanks

**Comment by josemvm** [comment]
hi @rldhont 

very, very nice and useful!
imagem

thanks for your work :)

**Comment by josemvm** [comment]
a little css issue (**mobile mode**):
imagem

**Comment by josemvm** [comment]
hi @rldhont 

if possible can you add the coordinates and the scale to the map?
they are very important , as you know


imagem

thanks

**Comment by josemvm** [comment]
- it seems to me that the **tooltip** is also  very suitable for this purpose

- the autocomplete attribute for locating tool is set to off...

     aaaa

**Comment by josemvm** [comment]
- the frame preserves the layer opacity but doesn't preserve the layer styles...

**Comment by rldhont** [comment]
@josemvm enhance UI
but I can't reproduce the issue of opacity and style.

**Comment by josemvm** [comment]
hi @rldhont 

sorry, you are right
the frame transports the layer opacity and the layer styles

the problem comes from blank spaces in the name of the layer style:

sty
i can open an issue about it


go ahead!

**Comment by rldhont** [comment]
@josemvm 
Does the embed controller is good for you ?
For the style you can open an issue. Thanks

**Comment by josemvm** [comment]
yes @rldhont, the embed controller it's a good idea, it's very good and very useful!

if you can take my suggestions (scale, coordinates, tooltip) into consideration it will be even better... :smiley:

thanks for your work

**Comment by rldhont** [comment]
@josemvm I have updated the code to take into account your suggestions. Test it ;-)

**Comment by josemvm** [comment]
@rldhont, it's much much better!

there are a minor problems in tools switcher, some tools do not close others...
can you try?

**Comment by josemvm** [comment]
the magnifying glass doesn't appear in serach tool...
imagem**<==**

**Comment by josemvm** [comment]
locating tool...
imagem

**Comment by josemvm** [comment]
a minor popup css...

pop

**Comment by rldhont** [comment]
Fixed:
* One tool at a time
* search tool button icon
* locate by layer list position

**Comment by rldhont** [comment]
@josemvm the force is forced to be displayed on the map

**Comment by josemvm** [comment]
@rldhont the map doesn't load in frame after last commit in `embed.classic.php` ...

**Comment by rldhont** [comment]
@josemvm sorry fixed

**Comment by josemvm** [comment]
:)
@rldhont please, check the related tables (Sous-Quartiers) in popup, case Districts, in Montpellier project...

**Comment by rldhont** [comment]
@josemvm what is the issue with related tables (Sous-Quartiers) in popup, case Districts, in Montpellier project ?

**Comment by josemvm** [comment]
can you see the features of related (Sous-Quartiers) table in popup?
e.g. MONTPELLIER CENTRE district

**Comment by rldhont** [comment]
Thans @josemvm for the reviews! I'll merge it now!

**Comment by josemvm** [comment]
thanks @rldhont to invite me to test and participate in this new nice feature!
 :star: :star: :star: :star: :star:

**Comment by josemvm** [comment]
hi @rldhont 

a css issue for personalized size

imagem

**Pull request merged**
