### PR TITLE
[FEATURE] Filter - search among a db layer with a form

### PR DESCRIPTION
**Pull request by mdouchin**
## Presentation

There is a new project `events.qgs` in the qgis demo repository with this feature activated via the master version of the Lizmap plugin. You can activate the filter tool for one or more database vector layers. I strongly advise PostgreSQL or GeoPackage

## Configuration

There is a new tab in the Lizmap plugin ( for QGIS 3 only) to let you configure the filter inputs based on the layer fields.

You must choose options for each field form input:

* **type**: one of the following value: `text`, `numeric`, `date`, `uniqueValues`
* **title**: the title to give to the input. For example "Choose a category" for a field called "category"
* **field**: the field name (in the database table)
* **Min date** and **Max date**: for `date` type only. If you have 2 fields, one for the start date and another for the end date, you can differentiate them. If you have only one date in your data, you must use the same field name for `Min date` and `Max date`.
* **format**:  for `uniqueValues` type only. Can be `select` which will show a combo box or `checkboxes` which will show one checkboxe for each distinct value
* **splitter**: for `uniqueValues` type only. Use if you want to split values by a separator. Ex: `'culture, environment'` can be split into `'culture'` and `'environment'` with the splitter `', '`

You can add one or more fields per layer. If you add fields from 2 or more différent layers, Lizmap Web Client will show a combo box to allow the user to choose the layer to filter, which will reset the filter and the form content.

The order of the lines in the configuration table is taken into account to show the field inputs in the form.

### Text

You can search any text. Autocompletion is enabled by default.

The filter built will be like: `"field" LIKE '%foo%'`

### Date

This input type will show a slider with 2 handles to allow to search between the two selected values. Two text inputs are also shown and can be used to manually set the min and max values.

The date is "truncated" to a date (no hour, minutes or seconds yet).

The slider step is hard coded and equals to 86400 = 1 day

The filter built will be like: TODO

### Numeric

This input type will show a slider with 2 handles to allow to search between the two selected values. 2 text inputs are also shown and can be used to manually set the min and max values.

The filter built will be like: TODO

### Unique values

Lizmap will query the data to get the distinct values of the field. You can choose two different input types: select or checkboxes.

The filter built will be like: TODO

TODO : speak about the splitter

#### Checkboxes

### CODE REVIEW

**Comment by mdouchin** [comment]
@mbernasocchi @josemvm @pcav could you please have a look ? I probably won't develop it more thant this stage for 3.3, but I would like some feedback. Main "doc" in this PR comment

**Comment by pcav** [comment]
Unsure about this. Wouldn't it be better to postpone it until ready also in the plugin?

**Comment by josemvm** [comment]
@mdouchin do you have a branch for download?

**Comment by josemvm** [comment]
sorry, ok branch: filter

**Comment by josemvm** [comment]
i can´t choose town...
imagem

**Comment by mdouchin** [comment]
@pcav @josemvm I have changed this feature a lot. Now the master plugin can be used (only in QGIS 3) to configure the filter. Doc needed, but some has been written above in the PR text

**Comment by josemvm** [comment]
hi @mdouchin 

imagem

this is the behavior after a fresh install...

**Comment by josemvm** [comment]
@pcav did you  already try it?

**Comment by mdouchin** [comment]
@pcav can you try it with a PostgreSQL layer please ?
The Geopackage db seems to needs its folder to be writable by the webserver to store temp files :( I added in the `lizmap/install/set_rights.sh` some comands to add the rights to the folder containing the events database. Could you try to run it and check if everything is ok ?

**Comment by pcav** [comment]
Trying it now, thanks.

**Comment by pcav** [comment]
Is this available in Lizmap 3.3rc1 and plugin 3.0.2?

**Comment by Abdelghafour1** [comment]
l'onglet de filtre n'est pas disponible dans le plugin lizmap pour QGIS 3, vous pouvez nous faire une capture d'écran sur ce nouveau onglet?

**Comment by mdouchin** [comment]
I just published a new plugin version :
https://plugins.qgis.org/plugins/lizmap/version/3.0.3/

**Comment by Abdelghafour1** [comment]
merci beaucoup mdouchin, vous faites un excellent travail

**Comment by dobignies** [comment]
It's a great addition for LWC. I just tested it with all types in a simple project with one layer but only text works partially with no autocompletion, no count, no zoom and export returns a broken ods file. Unique type shows only title for checkbox or an empty combo box. Numeric and date didn't work at all. I'm using postgresql 11, master LWC and 3.0.3 plugin. Is there any extra setup in database or qgis?

**Comment by mdouchin** [comment]
I forgot to add the filter module in the right configuration file, to allow it to be installed. Could you try last version of the release_3_3 branch ? Diff here : https://github.com/3liz/lizmap-web-client/commit/2bc50ff61c077ded44673a3e72d209f54eb02dc0

Please create a new issue regarding this feature, since this PR is closed and merged

**Comment by josemvm** [comment]
thanks @mdouchin :-)

very nice!!!
but also very slow for searches between dates...

**Comment by josemvm** [comment]
:+1

**Comment by mdouchin** [comment]
> but also very slow between criteria changes...

do you have proper indexes in your test table ? For example 

* for dates

```sql
CREATE INDEX ON your_schema.your_table (start_date, end_date DESC);
```

* for the text autocompletion, LIKE is used, so you should add a trigram index to speed up things

```sql
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX ON your_schema.your_table USING GIN (your_field gin_trgm_ops);
```

**Comment by josemvm** [comment]
for now i'm using the "Touristic events around Montpellier" project

**Comment by dobignies** [comment]
It works nicely now! Many thanks mdouchin

**Comment by saeri-ims** [comment]
Hello i am very interested in this new "filter data with form" but can anyone let me know if on the server side QGIS server 3 is needed? i tested the plugin and i cannot see displayed the filter icon among the icons on the left hand side of the screen.

What i have done:
I have downloaded the latest plugin and set up a project in QGIS 3.4 LTR. The data i am using in the project and for the filter data with form are coming from a database in postgres 10. On the server, which published the webGIS, i have Lizmap version 3.2.1 and finally the QGIS server version is >= 2.18

So, as you all managed to use the plugin, my only wonder is about the version of QGIS server. Am i correct or is there something else?

Many thanks, iLaria

**Comment by buoncri** [comment]
As wrote in this thread, in the first post under "Configuration", i read that plugin is for qgis3.

**Comment by saeri-ims** [comment]
Yes i had read that text, but i didn't realise, my ignorance about server and QGIS versions, that the two go strictly together.

Just a question, which i can log as request later on if necessary, would you or any lizmap developer recommend a lizmap admin to start publishing webGIS services using lizmap 3.3 rc, QGIS server3 and QGIS 3? Is the current release candidate stable and reliable enough OR it is better to wait?

Thanks.

**Pull request merged**
