### PR TITLE
Fix layer tree parsing for QGIS 3.22 project

### PR DESCRIPTION
**Pull request by rldhont**
Fixing some bugs:
* Getting shortName for layer tree group
* Gettting showFeatureCount for layer tree

Funded by 3Liz

### CODE REVIEW

**Comment by nboisteault** [comment]
@rldhont I have manually tested `Getting shortName for layer tree group`. It is ok now with 3.16 and 3.22. I'm going to add Cypress tests for it and also showFeatureCount and mutually exclusive groups.

**Comment by rldhont** [comment]
Thanks @nboisteault

**Comment by nboisteault** [comment]
@rldhont I've pushed tests on master https://github.com/3liz/lizmap-web-client/commit/932167d17fc76ef36184df95575e0b316d6c7065. You can rebase and launch tests.

**Comment by rldhont** [comment]
All is green!

**Review by nboisteault — APPROVED** [review]

**Pull request merged**
