### PR TITLE
Fix server URL when using FCGI for the Lizmap entrypoint

### PR DESCRIPTION
**Pull request by Gustry**
Fix server URL when using FCGI for the Lizmap entrypoint

### CODE REVIEW

**Comment by rldhont** [comment]
It seems good to me

**Comment by rldhont** [comment]
@Gustry 3.5.1 or after ?

**Comment by Gustry** [comment]
3.5.1, the FCGI URL is currently broken without this PR.

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
@Gustry can you add interface print to explain the issue and result

**Review by laurentj — APPROVED** [review]
lgtm

**Review by nboisteault — APPROVED** [review]

**Pull request merged**
