### PR TITLE
fix loading custom layout of dataviz plot with id 0

### PR DESCRIPTION
**Pull request by ygorigor**
* Ticket : fix https://github.com/3liz/lizmap-web-client/issues/2068

### CODE REVIEW

**Comment by Gustry** [comment]
Do you still have the issue #2068 ?

**Comment by ygorigor** [comment]
It seems that only me have this issue, so I closed it

**Comment by Gustry** [comment]
Maybe not only you, but maybe nobody noticed or not a lot of people are using this feature in LWC.
If this is fixing the issue, then it must be fixed upstream, no ?
You closed this PR, not the issue.

My colleagues will do a PR/issue triaging session in a few hours.

**Review by rldhont — APPROVED** [review]

**Review by nboisteault — APPROVED** [review]
Thanks.

**Pull request merged**
