### PR TITLE
Filter performance - Avoid to launch many useless GETFILTERTOKEN request

### PR DESCRIPTION
**Pull request by mdouchin**
Funded by Le Grand Narbonne https://www.legrandnarbonne.com/

### CODE REVIEW

**Comment by nboisteault** [comment]
@mdouchin I launch Cypress as there is an issue with playwright. If tests are ok, I'm ok.

**Comment by mdouchin** [comment]
@nboisteault test has already been run, and it failed because of the new "print" button in the popup and the corresponding test which has not been actualized ;)

**Comment by Gustry** [comment]
The regression is coming from https://github.com/3liz/lizmap-web-client/pull/3383

**Comment by Gustry** [comment]
FYI the `run cypress` label has no effect on these branches. Only on 3.5 as there isn't any playright test.

**Comment by Gustry** [comment]
Error cypress is on master as well : https://github.com/3liz/lizmap-web-client/actions/runs/3985749533/jobs/6833503093
I'm merging this PR.

**Pull request merged**
