### PR TITLE
Tests on the landingpage with XPath and opacity

### PR DESCRIPTION
**Pull request by Gustry**
I can confirm that reverting PR #5011 solves the 500.

The purpose was not to merge this PR, but to understand why the E2E was OK on PR #5011.
While there is a Cypress test about the landing page :
https://github.com/3liz/lizmap-web-client/blob/release_3_8/tests/end2end/cypress/integration/projects_homepage-ghaction.js

I can confirm there is a cache issue.

I tried to empty the redis database : 

```
➜ docker exec -it lizmaprelease_3_8_test_redis redis-cli flushall
OK
```

### CODE REVIEW

**Comment by Gustry** [comment]
CC @mind84 and @rldhont 

 I just want to trust our E2E test suite and avoid any regression like this one.

**Comment by mind84** [comment]
Hi @Gustry @rldhont,

I'm preparing the fix for the 500 error. Basically consists in a manual backport of the commit https://github.com/3liz/lizmap-web-client/commit/1e9be742fe5b70ff744ff40ad66951460ccf0a8d

**Comment by rldhont** [comment]
I also working on speed up main view to parse only project main data.

**Comment by Gustry** [comment]
Thanks for your debug both with your 2 PRs.

Just to clarify, I didn't mean at all to merge this PR ;-)
As I said, I was just curious at the beginning about E2E tests ;-)

**Comment by mind84** [comment]
> Thanks for your debug both with your 2 PRs.

 You are welcome!

> Just to clarify, I didn't mean at all to merge this PR ;-) As I said, I was just curious at the beginning about E2E tests ;-)

Yep, no worries at all :smile: ! However, even if you decide to regress on this PR, that's perfectly fine with me! There's no point in trying to force things in a way that causes more problems than necessary!

Thanks!

**Pull request closed without merging**
