### PR TITLE
[Bugfix] Defined default repository rights

### PR DESCRIPTION
**Pull request by rldhont**
To help creating and defining lizmap repository, default rights are now provided to the user.

The default rights are :
* For Anonymous users
  * View projects in the repository
* For users (default group for authenticated users)
  * View projects in the repository
  * Display projects WMS links
  * Allow export of layers
* For admins
  * View projects in the repository
  * Display projects WMS links
  * Allow export of layers
  * Use the Edition tool

lizmap-default-repository-rights

Funded by 3Liz https://3Liz.com

### CODE REVIEW

**Review by mdouchin — APPROVED** [review]
👌

**Review by Gustry — CHANGES_REQUESTED** [review]
For me, there is an UX issue if the user needs to scroll **at the bottom** if these checkbox are not stored by default.

There is a message at the top saying : 

> The repository data have been saved.
You can now configure the rights for this repository.

I know the second part of the message is explaining, but it's not clear for the end user, they might not know there is a button at the bottom. A lot of users might think "ok, it's enough, it looks alright, let's go out of this page."

**Review by laurentj — APPROVED** [review]
~~lgtm~~ I didn't see the comment of @Gustry

**Comment by rldhont** [comment]
@Gustry with this fix, rights can be set at the creation!

**Review by Gustry — APPROVED** [review]
I gave it a quick try, whoua, confusing to have one step less in repository creation !

LGTM when the item below is fixed :

* [ ] Menu item issue

image


Then clicking "Create a repository"

image


For my self, **later**, we do that after the release : 

* [ ] Login/password in test must be stored outside by environment variable etc

**Comment by rldhont** [comment]
Thanks @Gustry to pointed the menu item issue. I have fixed it.

**Pull request merged**
