### PR TITLE
PHPStan fix config file

### PR DESCRIPTION
**Pull request by rldhont**
Funded by 3liz

### CODE REVIEW

**Comment by rldhont** [comment]
To run phpstan locally, I have run composer update in lizmap directory.

**Comment by rldhont** [comment]
@laurentj last errors is about jApp.

**Review by laurentj — APPROVED** [review]
lgtm

**Review by mdouchin — APPROVED** [review]

**Comment by rldhont** [comment]
@laurentj to fix all phpstan error, the php docstring of jApp as to be fixed https://github.com/jelix/jelix/pull/377

**Pull request merged**
