### PR TITLE
Better digitizing + redlining

### PR DESCRIPTION
**Pull request by nboisteault**
Sponsored by [PNR Ballon des Vosges](https://www.parc-ballons-vosges.fr/).

### CODE REVIEW

**Comment by nboisteault** [comment]
@mdouchin @rldhont WIP

**Comment by josemvm** [comment]
hi @nboisteault is it possible to add labels to the drawings?

**Comment by mdouchin** [comment]
Hi @josemvm We have chosen not to do it for future 3.4. It will be added in next releases if really needed by many users. We try to not complexify the UI

**Comment by josemvm** [comment]
@nboisteault drawings without annotations looks like beer without malt... ;-)
thanks for your great work on LWC!

**Comment by nboisteault** [comment]
> @nboisteault drawings without annotations looks like beer without malt... ;-)
> thanks for your great work on LWC!

Or suggestions without pull requests... ;-)

**Comment by arno974** [comment]
Thanks for this feature !

**Pull request merged**
