### PR TITLE
[docker] Fix entrypoint about an error with script.php

### LINKED ISSUE #2067: Docker image fail with  Could not open input file: /scripts/script.php
### What is the bug?
When trying to run lizmap-docker-compose with the latest lizmap 3.4 Docker image, it fails with  the error 
`Could not open input file: /scripts/script.php` - cf https://github.com/3liz/lizmap-docker-compose/issues/9

### Steps to reproduce the issue

1. Download latest lizmap-web-client docker image 
2. Run the [lizmap-docker compose stack](https://github.com/3liz/lizmap-docker-compose) in a fresh environment 
3. The lizmap container fails with `Could not open input file: /scripts/script.php`

### Expected behavior
The lizmap container should run without error

### Screenshots and logs
```
lizmap_1  | + su -c 'php /scripts/script.php jcommunity~user:create -v --no-error-if-exists --admin --reset   admin'
lizmap_1  | Could not open input file: /scripts/script.php
lizmap-docker-compose_lizmap_1 exited with code 1
```

Apperently it sesems related to a `$APPDIR` environnement variable which is not initialized.

### PR DESCRIPTION
**Pull request by laurentj**
* Ticket : fix #2067
* Funded by 3liz

### CODE REVIEW

**Comment by nboisteault** [comment]
@dmarteau Could you build a docker image with this patch to test?

**Comment by dmarteau** [comment]
Build the docker image with: `make docker-build-ci` 

This create an image name: `3liz/lizmap-web-client:3.5.0-pre-<commit>`

Then running docker  compose with that image gives the error:
````
make run LIZMAP_VERSION_TAG=3.5.0-pre-<commit>
...
lizmap_1  | + LIZMAP_USER=1001
lizmap_1  | + LIZMAP_ADMIN_LOGIN=admin
lizmap_1  | + LIZMAP_ADMIN_EMAIL=root@local.localhost
lizmap_1  | + '[' '!' -z ]
lizmap_1  | + cp -aR lizmap/var/config.dist/config lizmap/var/config.dist/lizmapConfig.ini.php.dist lizmap/var/config.dist/localconfig.ini.php.dist lizmap/var/config
lizmap_1  | + '[' '!' -f lizmap/var/config/lizmapConfig.ini.php ]
lizmap_1  | + cp lizmap/var/config/lizmapConfig.ini.php.dist lizmap/var/config/lizmapConfig.ini.php
lizmap_1  | + '[' '!' -f lizmap/var/config/localconfig.ini.php ]
lizmap_1  | + cp lizmap/var/config/localconfig.ini.php.dist lizmap/var/config/localconfig.ini.php
lizmap_1  | + '[' '!' -f lizmap/var/config/profiles.ini.php ]
lizmap_1  | + cp lizmap/var/config/profiles.ini.php.dist lizmap/var/config/profiles.ini.php
lizmap_1  | cp: can't stat 'lizmap/var/config/profiles.ini.php.dist': No such file or directory

````

**Comment by dmarteau** [comment]
Going a bit further: 

```
lizmap_1  | + chown -R 1001:1001 lizmap/www
lizmap_1  | + update-config.php
lizmap_1  | + php lizmap/install/installer.php
lizmap_1  | PHP Deprecated:  the config file defaultconfig.ini.php is deprecated and will be removed in the next major release in /www/lib/jelix/core/jApp.class.php on line 164
lizmap_1  | PHP Fatal error:  Uncaught Exception: (23)The file /www/lizmap/var/config/defaultconfig.ini.php doesn't exist in /www/lib/jelix/utils/jIniFileModifier.class.php:78
lizmap_1  | Stack trace:
lizmap_1  | #0 /www/lib/jelix/installer/jInstaller.class.php(242): jIniFileModifier->__construct('/www/lizmap/var...')
lizmap_1  | #1 /www/lizmap/install/installer.php(14): jInstaller->__construct(Object(textInstallReporter))
lizmap_1  | #2 {main}
lizmap_1  |   thrown in /www/lib/jelix/utils/jIniFileModifier.class.php on line 78
```

AMHA the docker image is completely broken and not tested as it should.

**Comment by nboisteault** [comment]
@laurentj is it something you want me to try fixing ?

**Comment by nboisteault** [comment]
@laurentj @dmarteau I have modified Lizmap-docker-compose README.md (https://github.com/3liz/lizmap-docker-compose/commit/c4912ca313deebc0d3c3945d6a06f45b6a082007) to give a workaround to this issue.

**Comment by laurentj** [comment]
@dmarteau it is not tested as it should, because there is no documentation, anywhere, that's says how to test the image.

> cp: can't stat 'lizmap/var/config/profiles.ini.php.dist': No such file or directory

I don't know why you have such error. This file is included into the generated package, which in turn is dezipped during the build of the image. IMHO you missed a step during your test, certainly because there is _no documentation about how to build and test the image_ ;-)

>the docker image is completely broken with 3.5.x

IMHO, it is completely broken on your machine, as the docker/ directory is strictly equals on both branch, master and 3.4.

Could you please provide a documentation about how to test the image?

I guess the begin of the documentation should be :

> * launch `make package docker-build-ci`
> * at the end of the execution of this command, it displays `Successfully tagged lizmap-web-client:X.Y.Z-D` where `X.Y.Z-D` are numbers. This is the version of the image. 
> * download sources files from https://github.com/3liz/lizmap-docker-compose/ : it has a docker compose file which defines a "stack" to run nginx+qgis+lizmap
> * in the directory of lizmap-docker-compose, execute `make start LIZMAP_VERSION_TAG=X.Y.Z-D` (by replacing `X.Y.Z-D` by the version you get previously above)

However, on my machine, the last command ends with an error : 

```
$ make start LIZMAP_VERSION_TAG=3.5.0-pre-59723866
...
docker-compose up
Creating network "lizmap-docker-compose_default" with the default driver
Pulling lizmap (3liz/lizmap-web-client:3.5.0-pre-59723866)...
ERROR: manifest for 3liz/lizmap-web-client:3.5.0-pre-59723866 not found: manifest unknown: manifest unknown
make: *** [Makefile:50 : run] Erreur 1
```

So probably a step or a parameter is missing somewhere in the todo list above...

**Comment by dmarteau** [comment]
The image may be tested exactly as described here with a proper stack set-up like lizmap stack compose: https://github.com/3liz/lizmap-web-client/pull/2078#issuecomment-770725074

> IMHO, it is completely broken on your machine, as the docker/ directory is strictly equals on both branch, master and 3.4.

Please refer to https://github.com/3liz/lizmap-docker-compose/issues/9

There is clearly a change/regression starting from delivered image starting with 3.4.0/3.4.1 and I don't knom what to do with it.

**Comment by dmarteau** [comment]
> ERROR: manifest for 3liz/lizmap-web-client:3.5.0-pre-59723866 not found: manifest unknown: manifest unknown

@laurentj the docker image ` 3liz/lizmap-web-client:3.5.0-pre-59723866`  simply does not exists on your machine.

**Comment by laurentj** [comment]
@dmarteau well, there is an existing image on my machine, that appears immediately after the `make package docker-build-ci` :

```
$ docker images | grep lizmap
lizmap-web-client                                  3.5.0-pre-59723866    4f083d536d07   9 minutes ago   128MB
```

**Comment by dmarteau** [comment]
> well, there is an existing image on my machine, that appears immediately after the make package docker-build-ci

ATM this image has to be retagged to  `3liz/lizmap-web-client:3.5.0-pre-59723866` to work with [lizmap-docker-compose](https://github.com/3liz/lizmap-docker-compose)

```
docker tag lizmap-web-client:3.5.0-pre-59723866 3liz/lizmap-web-client:3.5.0-pre-59723866
```

**Comment by laurentj** [comment]
The PR #2086 includes my patch. I can close this PR.

**Pull request closed without merging**
