### PR TITLE
Reverse geometry button: when editing a line or polygon feature, you can reverse vertices order.

### PR DESCRIPTION
**Pull request by nboisteault**
* Funded by city of [Avignon](http://www.avignon.fr/)

When editing a line or polygon feature, you can now reverse vertices order. This is useful for streets when their circulation orientation is reversed for example.

reverse_geom

### CODE REVIEW

**Comment by rldhont** [comment]
@nboisteault can you extend the description of the PR for the changelog and documentation ?

**Comment by Gustry** [comment]
Nice @nboisteault :)

> @nboisteault can you extend the description of the PR for the changelog and documentation ?

It would be nice to somehow keep track like QGIS, having ticket created auto in the doc. On my wishlist :)

**Comment by nboisteault** [comment]
> Nice @nboisteault :)
> 
> I think for the test project, we will need a single one (later or now) for geometry operation. Having a single project for just "reversed" will take us more time on testing each scenario. Maybe rename it to be more generic ? Feel free to skip, just my 2 cents.
> 
> > @nboisteault can you extend the description of the PR for the changelog and documentation ?
> 
> It would be nice to somehow keep track like QGIS, having ticket created auto in the doc. On my wishlist :)

I might merge this test project with some others but I'd like to have this test been made by Cypress with screenshot comparison so we won't spend time manually test this feature. We'll have to update QGIS/Lizmap project files though.

**Comment by nboisteault** [comment]
Doc made : https://github.com/3liz/lizmap-documentation/commit/e33af28da005e859ac914c4509c15487a59e9ae2

**Pull request merged**
