### PR TITLE
Improvement of upload content into feature forms and image editor for uploaded images

### PR DESCRIPTION
**Pull request by laurentj**
The support of uploaded file has been improved into feature forms. Better mechanism to check the uploaded files.
There is also now an image editor when the user wants to upload an image. The image can be cropped, rotated, and is resized automatically if it is higher than a size we can set into the lizmap configuration.

* Ticket: #1304
* Ticket: #572
* Funded by Mairie d'Avignon

### CODE REVIEW

**Comment by laurentj** [comment]
It probably fixes also #2427

**Comment by nboisteault** [comment]
Great work @laurentj ! I have tested and i just have an error message in console when canceling image modification, not sure it is important. Also I noticed that there is no cross at top right to close the image modification window.
Peek 30-11-2021 16-59

There is some work needed for small screens. Do you want me to work on this?

image

**Comment by laurentj** [comment]
@nboisteault  I fixed the JS error, and hide the button.

It would be fine if you could work on the mobile version. But it will not easy, as the dialog has fixed size, and the canvas should have specific size, for rotation etc. (see the code into imageSelector.js)

**Comment by nboisteault** [comment]
@laurentj good! How it possible to translate the `Cancel` button?

image

**Comment by nboisteault** [comment]
Concerning dialog size, it is ok when putting smartphone in landscape position, so we can consider it is not an issue.

**Review by nboisteault — APPROVED** [review]
Just the Cancel button to translate if possible.

**Comment by laurentj** [comment]
cancel button translated :-)

**Comment by nboisteault** [comment]
@laurentj to run Cypress in CI you need to allow this action in your settings then:
cypress_manual

**Pull request merged**
