### PR TITLE
Tests - Use qgis-plugin-manager to install all plugins

### PR DESCRIPTION
**Pull request by Gustry**
Use qgis-plugin-manager to install plugins

Drawback for now, it's only downloading plugin released version, based on a tag.

### CODE REVIEW

**Comment by Gustry** [comment]
PR ready

- Keep legacy way for "Lizmap server", from packages.3liz.org
- Use qgis-plugin-manager for wfsoutputextension and atlasprint, stable releases from plugins.qgis.org

This PR will increase our number of downloads on plugins.qgis.org

Merging

**Comment by rldhont** [comment]
@Gustry the `qgis-plugin-manager update` command returns `[Errno 13] Permission denied: 'https-plugins-qgis-org-plugins-plugins-xml-qgis-3-22.xml'`

**Comment by rldhont** [comment]
backports ?

**Comment by Gustry** [comment]
> backports ?

Already done

> [Errno 13] Permission denied: 'https-plugins-qgis-org-plugins-plugins-xml-qgis-3-22.xml

Remove your old files/directories

```bash
rm -rf qgis-server-plugins
mkdir qgis-server-plugins
make build-plugins
```

Does it fix your issue ?

**Comment by rldhont** [comment]
@Gustry GH cypress end2end tests failed :
```
Archive:  /tmp/lizmap_server.master.zip
checkdir:  cannot create extraction directory: /srv/plugins
           Permission denied
QGIS Server WfsOutputExtension and AlasPrint plugins
./add_server_plugins.sh: line 20: qgis-plugin-manager: command not found
Stable releases from http://plugins.qgis.org/
./add_server_plugins.sh: line 21: qgis-plugin-manager: command not found
./add_server_plugins.sh: line 23: qgis-plugin-manager: command not found
./add_server_plugins.sh: line 24: qgis-plugin-manager: command not found
Error: Process completed with exit code 127.
```

**Comment by rldhont** [comment]
> @Gustry GH cypress end2end tests failed :
> 
> ```
> Archive:  /tmp/lizmap_server.master.zip
> checkdir:  cannot create extraction directory: /srv/plugins
>            Permission denied
> QGIS Server WfsOutputExtension and AlasPrint plugins
> ./add_server_plugins.sh: line 20: qgis-plugin-manager: command not found
> Stable releases from http://plugins.qgis.org/
> ./add_server_plugins.sh: line 21: qgis-plugin-manager: command not found
> ./add_server_plugins.sh: line 23: qgis-plugin-manager: command not found
> ./add_server_plugins.sh: line 24: qgis-plugin-manager: command not found
> Error: Process completed with exit code 127.
> ```

Seems to be fixed with https://github.com/3liz/lizmap-web-client/commit/ba5fe7ac7ed06c1d62c3a7b28cc8bf32ad996dd6

**Pull request merged**
