### PR TITLE
[Bugfix] Use form check in Ajax Save new feature

### PR DESCRIPTION
**Pull request by rldhont**
In the Ajax saveNewFeature method, the form check was not used to return before saveToDb.

### CODE REVIEW

**Comment by rldhont** [comment]
To simplify the method `saveNewFeature` and avoid duplicated codes, we can use `$qgisForm->check()` instead of `$form->check()`, isn't it @laurentj ?

**Comment by nboisteault** [comment]
@rldhont is it just to be reviewed or also tested? If it needs tests, what is the scenario?

**Comment by rldhont** [comment]
I am waiting for @laurentj comments. I would like to know if I can do more changes.

@laurentj has develop this method, he can get you a scenario to test it.

**Review by laurentj — APPROVED** [review]

**Comment by laurentj** [comment]
> To simplify the method `saveNewFeature` and avoid duplicated codes, we can use `$qgisForm->check()` instead of `$form->check()`, isn't it @laurentj ?

Probably. I don't know. but we have to be care about content we returned. For example `qgisForm::check()` stores error messages into the form, se we would have to retrieve them in order to return them as json content, as the actuel code.

**Comment by laurentj** [comment]
at least, the use of `$qgisForm->check()` should be an other PR

**Comment by rldhont** [comment]
@laurentj thanks for review, I'll do a new PR.

**Pull request merged**
