### PR TITLE
Bootstrap 5 tooltip on FeatureToolbar component

### PR DESCRIPTION
**Pull request by mind84**
Follow this PR https://github.com/3liz/lizmap-web-client/pull/4752

Linked to https://github.com/3liz/lizmap-web-client/pull/4768 and https://github.com/3liz/lizmap-web-client/pull/4635

Funded by Faunalia

### CODE REVIEW

**Comment by nboisteault** [comment]
Hi @mind84, sorry but the test still fail with this PR.

**Comment by mind84** [comment]
> Hi @mind84, sorry but the test still fail with this PR.

yes, I see, very annoying :D

I'll put this on draft and push some version of update n_to_m_relation.spec.js with changes you suggested in #4752

Let's see

Thanks

**Comment by mind84** [comment]
@nboisteault 

I think I did it without changing the` n_to_m_relations.spec.js`, so I can keep the PR separate.

Issue is related `unlink` option on the feature toolbar and its `tooltip`. The tooltip il placed in absolute position within the `body`, so after clicking the unlink button the corresponding `feature toolbar` is removed from DOM as a consequence of the attribute table update. This, apparently, leaves the tooltip orphan on the page (which is unexpected since the trigger is forced on `hover`). 

So I specify also the `container` option on tooltip initialization, to force the tooltip to be within the toolbar.

I think that for the feature toolbar component this behavior could be considered correct, I don't know for others tooltip

**Comment by nboisteault** [comment]
@mind84 great investigation!
Thank you for this PR.

**Review by nboisteault — APPROVED** [review]

**Pull request merged**
