### PR TITLE
Dataviz - Correctly show the plot in the parent popup when the 'only show in child popup' is active

### LINKED ISSUE #2555: [Bug]: Dataviz, the chart must be displayed in the main panel if we want to display it only in a popup
### What is the bug?

If we want to display a filtered chart only in the popup of the parent, it's required to have it as well in the dataviz main panel.

So for now, the "only show in child popup" mustn't be checked.

This is a regression.

### Steps to reproduce the issue

Make a chart with "only show in child popup" checked, it won't be displayed.

### Lizmap version

3.4.6

### QGIS desktop version

3.10

### QGIS server version

3.10

### Operating system

All

### Browsers

Firefox

### Browsers version

Latest firefox

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mdouchin**
Fixes the regression: 

> If we want to display a filtered chart only in the popup of the parent, it's required to have it as well in the dataviz main panel. So for now, the "only show in child popup" mustn't be checked.

* Ticket : fix #2555
* Funded by 3liz

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
The PHPStan test failed will be fixed by #2577

**Comment by rldhont** [comment]
@mdouchin can you rebase your branch to get #2577

**Comment by mdouchin** [comment]
> @mdouchin can you rebase your branch to get #2577

done

**Comment by rldhont** [comment]
@mdouchin I have fix the changelog 3.4, can you update it for this fix ?

**Comment by Gustry** [comment]
> @mdouchin I have fix the changelog 3.4, can you update it for this fix ?

Editing changelog in a PR for LWC is not the best. 3.5 is affected as well. The content of these files is often quite different in the 3 branches master, release_3_5, release 3_4.

**Comment by rldhont** [comment]
@mdouchin you can merge without changelog

**Pull request merged**
