### PR TITLE
[Bugfix] Get form modified controls

### PR DESCRIPTION
**Pull request by rldhont**
## Description

We have an issue in the way lizmap managed editable fields when the form is applied.

This commit try to indentified only modified fields even if the fields is hidden or not used in the drag and drop form.

Funded by Conseil Départemental des Pyrénées Atlantiques

### CODE REVIEW

**Review by nboisteault — APPROVED** [review]
Tested. OK.

**Comment by josemvm** [comment]
@rldhont something wrong with this fix... https://github.com/3liz/lizmap-web-client/commit/5e1c2d50afbec07a5e22cc79aa4ab5c94b18f768#diff-2fb80b5b3e2578a5bd07b7e7799fe60f1fcd6173ace1f525031957cf7dcdaa1c

**Comment by josemvm** [comment]
edition problems with "not-null constraint" in postgresql table - edition stops work

log lwc:
2020-10-27 16:38:39	10.27.10.58	error	An error has been raised when saving form data edition to db : 
2020-10-27 16:38:39	10.27.10.58	error	2020-10-27 16:38:39	xx.xx.xx.xx	[403]	query inválida (ERROR:  null value in column "ed_classe" violates not-null constraint

**Comment by nboisteault** [comment]
@josemvm open ticket with all information please.

**Comment by josemvm** [comment]
everything is ok after last commits. thanks

**Pull request merged**
